.gitignore
README.md
example/main.tf
internal/app/tfsec/azurerm_open_network_security_rules_test.go
internal/app/tfsec/azurerm_unencrypted_data_lake_store_test.go
internal/app/tfsec/azurerm_unencrypted_managed_disk_test.go
internal/app/tfsec/azurerm_virtual_machine_with_password_authentication_test.go
internal/app/tfsec/checks/azurerm_open_network_security_rules.go
internal/app/tfsec/checks/azurerm_unencrypted_data_lake_store.go
internal/app/tfsec/checks/azurerm_unencrypted_managed_disk.go
internal/app/tfsec/checks/azurerm_virtual_machine_with_password_authentication.go

| Code    | Provider | Description |
|---------|----------|-------------|
| AZU001  | azurerm  | An inbound network security rule allows traffic from `/0`.
| AZU002  | azurerm  | An outbound network security rule allows traffic to `/0`.
| AZU003  | azurerm  | Unencrypted managed disk.
| AZU004  | azurerm  | Unencrypted data lake store.
| AZU005  | azurerm  | Password authentication in use instead of SSH keys.

Add azure support

---

cmd/tfsec/main.go
internal/app/tfsec/aws_acl_test.go
internal/app/tfsec/aws_bucket_logging_test.go
internal/app/tfsec/aws_classic_test.go
internal/app/tfsec/aws_http_test.go
internal/app/tfsec/aws_not_internal_test.go
internal/app/tfsec/aws_open_security_group_rule_test.go
internal/app/tfsec/aws_open_security_group_test.go
internal/app/tfsec/aws_outdated_ssl_test.go
internal/app/tfsec/aws_public_ip_test.go
internal/app/tfsec/aws_public_test.go
internal/app/tfsec/aws_task_definition_includes_sensitive_data_test.go
internal/app/tfsec/aws_unencrypted_block_device_test.go
internal/app/tfsec/azurerm_open_network_security_rules_test.go
internal/app/tfsec/azurerm_unencrypted_data_lake_store_test.go
internal/app/tfsec/azurerm_unencrypted_managed_disk_test.go
internal/app/tfsec/azurerm_virtual_machine_with_password_authentication_test.go
internal/app/tfsec/checks/aws_bucket_logging.go
internal/app/tfsec/checks/aws_http.go
internal/app/tfsec/checks/aws_open_security_groups.go
internal/app/tfsec/checks/aws_unencrypted_block_device.go
internal/app/tfsec/checks/azurerm_unencrypted_managed_disk.go
internal/app/tfsec/checks/azurerm_virtual_machine_with_password_authentication.go
internal/app/tfsec/checks/result.go
internal/app/tfsec/checks/util.go
internal/app/tfsec/generic_sensitive_attributes_test.go
internal/app/tfsec/generic_sensitive_locals_test.go
internal/app/tfsec/generic_sensitive_variables_test.go
internal/app/tfsec/scanner/scanner.go
internal/app/tfsec/setup_test.go

Allow HTTP alb when redirecting to HTTPS

---

internal/app/tfsec/aws_unencrypted_block_device_test.go
internal/app/tfsec/checks/aws_acl.go
internal/app/tfsec/checks/aws_bucket_logging.go
internal/app/tfsec/checks/aws_classic.go
internal/app/tfsec/checks/aws_http.go
internal/app/tfsec/checks/aws_not_internal.go
internal/app/tfsec/checks/aws_open_security_group_rules.go
internal/app/tfsec/checks/aws_open_security_groups.go
internal/app/tfsec/checks/aws_outdated_ssl.go
internal/app/tfsec/checks/aws_public.go
internal/app/tfsec/checks/aws_public_ip.go
internal/app/tfsec/checks/aws_task_definition_includes_sensitive_data.go
internal/app/tfsec/checks/aws_unencrypted_block_device.go
internal/app/tfsec/checks/azurerm_open_network_security_rules.go
internal/app/tfsec/checks/azurerm_unencrypted_data_lake_store.go
internal/app/tfsec/checks/azurerm_unencrypted_managed_disk.go
internal/app/tfsec/checks/azurerm_virtual_machine_with_password_authentication.go
internal/app/tfsec/checks/generic_sensitive_attributes.go
internal/app/tfsec/checks/generic_sensitive_locals.go
internal/app/tfsec/checks/generic_sensitive_variables.go
internal/app/tfsec/checks/google_unencrypted_disk.go
internal/app/tfsec/checks/google_unencrypted_storage_bucket.go
internal/app/tfsec/parser/block.go
internal/app/tfsec/scanner/check.go
internal/app/tfsec/scanner/context.go
internal/app/tfsec/scanner/scanner.go
internal/app/tfsec/setup_test.go

Fix false positives for block devices which are encrypted by default

---

README.md
internal/app/tfsec/aws_task_definition_includes_sensitive_data_test.go
internal/app/tfsec/ignore_test.go
internal/app/tfsec/scanner/scanner.go

Ignore specific checks

---

README.md
internal/app/tfsec/aws_unencrypted_sns_topic_test.go
internal/app/tfsec/aws_unencrypted_sqs_queue_test.go
internal/app/tfsec/checks/aws_unencrypted_sns_topic.go
internal/app/tfsec/checks/aws_unencrypted_sqs_queue.go

Add SQS queue and SNS topic encryption checks

---

README.md
internal/app/tfsec/aws_unencrypted_s3_bucket_test.go
internal/app/tfsec/checks/aws_unencrypted_s3_bucket.go
internal/app/tfsec/checks/aws_unencrypted_sns_topic.go
internal/app/tfsec/checks/aws_unencrypted_sqs_queue.go

Add check for unencrypted S3 buckets

---

README.md
internal/app/tfsec/aws_missing_description_for_security_group_test.go
internal/app/tfsec/checks/aws_missing_description_in_security_group.go

Add check for missing description in security groups

---

internal/app/tfsec/parser/parser.go

Fix bug in module block parsing

---

README.md
cmd/tfsec/main.go
go.mod
internal/app/tfsec/formatters/checkstyle.go
internal/app/tfsec/formatters/csv.go
internal/app/tfsec/formatters/default.go
internal/app/tfsec/formatters/json.go
internal/app/tfsec/parser/range.go
internal/app/tfsec/scanner/result.go

Add new output formats

---

go.mod
scripts/build.sh

Disable cgo

---

.gitignore
README.md
internal/app/tfsec/aws_no_kms_key_autorotate_test.go
internal/app/tfsec/checks/aws_no_kms_key_autorotate.go

- adds AWSNoKMSAutoRotate check (AWS019)
- adds AWSNoKMSAutoRotate test cases

adds KMS auto-rotation check (closes #31)

---

README.md

Add Chocolatey Installation option for windows users
Some of us have to unfortunately use windows, lets at least make it comfortable!

Add Chocolatey Install Option

---

internal/app/tfsec/aws_no_ecr_repository_scan_test.go
internal/app/tfsec/checks/aws_ecr_image_scan.go

Adding check for ECR image scan enabled or disabled
#36

Ensure ecr repository image scans are enabled

---

internal/app/tfsec/aws_unencrypted_kinesis_streams_test.go
internal/app/tfsec/checks/aws_unencrypted_kinesis_streams.go

adding kinesis stream check #33

adding kinesis stream check #33

---

internal/app/tfsec/parser/parser.go

Introduces a parse result caching quick fix
This should fix the "long parsing issue" #113 that we can observe on a variety of repositories. Looking into this, we noticed that the unfortunate mixture of parsing and building evaluation contexts leads to A LOT of useless parsing under certain real-world conditions. 
In order get a quick fix out, we extend @ttacon's band-aid to also cache the parsing result of `parseModuleBlocks` given their fully resolved path.
Please take a look whether this feasible at all or may break things in an unexpected way. Testing this on a few real-world projects seemed OK so far, but that is only anecdotal evidence.
Thank you for creating tfsec! It is a great idea and a great tool! ❤️

Add parse result caching

---

internal/app/tfsec/checks/generic_sensitive_attributes.go
internal/app/tfsec/generic_sensitive_attributes_test.go

Add false positive whitelist for GEN003

---

internal/app/tfsec/scanner/check.go

Moved warning to stderr

---

internal/app/tfsec/aws_open_security_group_test.go
internal/app/tfsec/checks/aws_open_security_groups.go
internal/app/tfsec/parser/block.go

Add support for dynamic blocks

---

internal/app/tfsec/aws_open_security_group_test.go
internal/app/tfsec/checks/aws_open_security_groups.go

Support multiple egress/ingress blocks in security groups

---

README.md
cmd/tfsec/main.go
internal/app/tfsec/module_scan_test.go
internal/app/tfsec/parser/parser.go
internal/app/tfsec/parser/parser_test.go
internal/app/tfsec/setup_test.go

Add option to exclude directories

---

internal/app/tfsec/azurerm_open_network_security_rules_test.go
internal/app/tfsec/checks/azurerm_open_network_security_rules.go

Check access param of azure sg rules

---

internal/app/tfsec/checks/google_unencrypted_storage_bucket.go
internal/app/tfsec/google_unencrypted_storage_bucket_test.go

Allow gcp bucket without default key

---

internal/app/tfsec/checks/generic_sensitive_attributes.go

Whitelist entry to avoid false positive gen003

---

README.md
cmd/tfsec/main.go
example/main.tf
internal/app/tfsec/module_scan_test.go
internal/app/tfsec/parser/parser.go
internal/app/tfsec/parser/parser_test.go
internal/app/tfsec/parser/tfvars.go
internal/app/tfsec/setup_test.go

Add support for tfvars files

---

.travis.yml
Dockerfile
Makefile
README.md

Publish images on build

---

internal/app/tfsec/aws_open_security_group_rule_test.go
internal/app/tfsec/aws_open_security_group_test.go
internal/app/tfsec/checks/aws_open_security_group_rules.go
internal/app/tfsec/checks/aws_open_security_groups.go

Add ipv6 support for aws security group rules

---

cmd/tfsec/main.go
internal/app/tfsec/formatters/checkstyle.go
internal/app/tfsec/formatters/csv.go
internal/app/tfsec/formatters/default.go
internal/app/tfsec/formatters/formatter.go
internal/app/tfsec/formatters/json.go
internal/app/tfsec/formatters/junit.go

out flag allows writing to a file instead std out

Add out flag

---

cmd/tfsec/main.go
internal/app/tfsec/formatters/text.go

Added text formatter without color formatting

added text formatter

---

README.md
internal/app/tfsec/aws_iam_no_password_reset_prevention_set_test.go
internal/app/tfsec/checks/aws_enforce_password_reuse_prevention.go

- warns if the password reuse count is less than 5 or not present

iam password reuse prevention

---

README.md
internal/app/tfsec/aws_provider_test.go
internal/app/tfsec/checks/aws_provider.go

Add check for AWS Provider containing access keys hardcoded

---

README.md
internal/app/tfsec/aws_cloudfront_does_not_have_waf_test.go
internal/app/tfsec/checks/aws_cloudfront_has_a_waf.go

Add check that cloudfront distribution has WAF enabled

---

README.md
internal/app/tfsec/aws_iam_policy_document_test.go
internal/app/tfsec/checks/aws_iam_policy_document.go

Add wildcard action in IAM policy document

---

CHECKS.md
CONTRIBUTING.md
Makefile
README.md
cmd/tfsec-docs/checks.go
cmd/tfsec-docs/main.go
internal/app/tfsec/checks/google_open_firewall_rules.go

First stab at documentation generator, very basic but #LittleAndOften 
- Generate the CHECKS.md file from the registered checks
- For now, run it as a pre-commit change to update.

adding tfsec docs for check file

---

README.md

Homebrew formula has been approved and merged, updating the instructions
to install on mac

Update homebrew instructions

---

AWS_CHECKS.md
AZURE_CHECKS.md
GENERAL_CHECKS.md
GOOGLE_CHECKS.md
README.md
cmd/tfsec-docs/checks.go
cmd/tfsec-docs/main.go
internal/app/tfsec/scanner/check.go

as the number of checks scale up, probably worth splitting out the files
that list the checks

Break out checks into individual files

---

Makefile
cmd/tfsec-docs/checks.go
cmd/tfsec-docs/main.go
cmd/tfsec-docs/templateWriteer.go
cmd/tfsec-docs/wiki.go
docs/AWS_CHECKS.md
docs/AZURE_CHECKS.md
docs/GENERAL_CHECKS.md
docs/GOOGLE_CHECKS.md
example/brew-validate.tf
scripts/update-wiki.sh

- updates the side bar
- adds missing skeleton entry for checks with no page
- Updates the category pages

Add Wiki shell generator

---

internal/app/tfsec/checks/aws_iam_password_policy_checks.go

Add the documentation components for password policy

Add the documentation components for password policy

---

internal/app/tfsec/checks/aws046.go
internal/app/tfsec/test/aws046_test.go

Allow wildcard for IAM 'deny'

---

internal/app/tfsec/formatters/default.go
internal/app/tfsec/parser/evaluator.go
internal/app/tfsec/parser/load_blocks.go
internal/app/tfsec/parser/load_dir.go
internal/app/tfsec/parser/load_module.go
internal/app/tfsec/parser/load_vars.go
internal/app/tfsec/parser/parser.go
internal/app/tfsec/scanner/scanner.go
internal/app/tfsec/timer/timer.go

Add statistics in default output

---

internal/app/tfsec/checks/azu006.go
internal/app/tfsec/test/azu006_test.go

Ensure AKS cluster has Network Policy configured

[#286] Added check for AKS cluster Network Policy

---

docs-website/_docs/custom_checks.md
example/custom/.tfsec/custom_tfchecks.json
example/custom/custom_check.tf
internal/app/tfsec/custom/custom_check.go
internal/app/tfsec/custom/processing.go
internal/app/tfsec/parser/attribute.go
internal/app/tfsec/parser/attribute_test.go

- update the documentation to reflect changes
- changed `MatchSpec` value to interface{} for increased flexibility
- added more checks for custom checks to validate

Adding isAny and isNone custom checks

---

docs-website/_docs/pr_commenter.md
internal/app/tfsec/checks/aws051.go
internal/app/tfsec/checks/aws052.go
internal/app/tfsec/parser/attribute.go
internal/app/tfsec/test/aws051_test.go
internal/app/tfsec/test/aws052_test.go

- check encryption on 
- `aws_rds_cluster` and 
- `aws_db_instance`

RDS Encryption checks

---

internal/app/tfsec/checks/aws053.go
internal/app/tfsec/parser/block.go
internal/app/tfsec/parser/block_test.go
internal/app/tfsec/test/aws053_test.go

Adding performance insights encryption checks from the previous PR that had failing tests and was in the old format

Rds performance insights encryption

---

internal/app/tfsec/checks/aws038.go

fixing typo s/greated/greater/ in AWS038

---

internal/app/tfsec/checks/azu011.go
internal/app/tfsec/checks/azu012.go
internal/app/tfsec/parser/attribute.go
internal/app/tfsec/test/azu011_test.go
internal/app/tfsec/test/azu012_test.go

add helper function to pull the value from a map
Closes #327
Closes #328

Add check for storage container not having public access

---

internal/app/tfsec/checks/azu012.go
internal/app/tfsec/checks/azu013.go
internal/app/tfsec/checks/azu014.go
internal/app/tfsec/test/azu012_test.go
internal/app/tfsec/test/azu013_test.go
internal/app/tfsec/test/azu014_test.go

Closes #321 
Closes #322 
Closes #325
Closes #326

Add checks for azure network rules on storage account

---

internal/app/tfsec/checks/azu012.go
internal/app/tfsec/checks/azu013.go
internal/app/tfsec/checks/azu014.go
internal/app/tfsec/checks/azu015.go
internal/app/tfsec/checks/azu016.go
internal/app/tfsec/test/azu015_test.go
internal/app/tfsec/test/azu016_test.go

Add more checks

---

internal/app/tfsec/checks/azu017.go
internal/app/tfsec/test/azu017_test.go

SSH not accessible from internet

---

internal/app/tfsec/checks/azu012.go
internal/app/tfsec/checks/azu013.go
internal/app/tfsec/checks/azu017.go
internal/app/tfsec/checks/azu018.go
internal/app/tfsec/checks/azu019.go
internal/app/tfsec/checks/gen001.go
internal/app/tfsec/checks/gen003.go
internal/app/tfsec/parser/attribute.go
internal/app/tfsec/parser/attribute_test.go
internal/app/tfsec/parser/block.go
internal/app/tfsec/parser/parser_test.go
internal/app/tfsec/scanner/check.go
internal/app/tfsec/scanner/context.go
internal/app/tfsec/test/azu018_test.go
internal/app/tfsec/test/azu019_test.go

Closes #296 
Closes #297 
Closes #319 
Closes #320

Add some additional helper functions and some sql checks

---

docs-website/_docs/custom_checks.md
example/custom/.tfsec/custom_tfchecks.json
example/custom/custom_check.tf
internal/app/tfsec/custom/custom_check.go
internal/app/tfsec/custom/processing.go
internal/app/tfsec/parser/attribute.go
internal/app/tfsec/parser/block.go

add more check actions
- lessThan, lessThanOrEqualTo, greaterThan, greaterThanOrEqualTo
- isEmpty for attributes and blocks
- update the docs
-

add more check actions

---

Dockerfile
scripts/build.sh

fixes https://github.com/tfsec/tfsec/issues/519

build statically linked binaries

---

README.md

I had to dig in the issues to find how to do it, from https://github.com/tfsec/tfsec/issues/92

Document how to ignore multiple rule at once

---

cmd/tfsec/main.go
docs-website/_docs/config.md
internal/app/tfsec/config/config.go
internal/app/tfsec/config/config_test.go

Also fixes a small bug where config files with the suffix `yml` where not being loaded correctly.

Also load exclude list from config and merge with flags

---

internal/app/tfsec/checks/aws052.go
internal/app/tfsec/test/aws052_test.go

Fix encrypted RDS check to look at storage_encrypted attribute

---

internal/app/tfsec/parser/attribute.go
internal/app/tfsec/parser/attribute_test.go

Matchspec contains autoscaling grp support

Matchspec contains autoscaling grp support

---

cmd/tfsec/main.go
example/good/good.tf
internal/app/tfsec/formatters/checkstyle.go
internal/app/tfsec/formatters/csv.go
internal/app/tfsec/formatters/default.go
internal/app/tfsec/formatters/formatter.go
internal/app/tfsec/formatters/json.go
internal/app/tfsec/formatters/junit.go
internal/app/tfsec/formatters/sarif.go
internal/app/tfsec/formatters/text.go

add concept of FormatOption 

---

internal/app/tfsec/checks/utils.go
internal/app/tfsec/parser/evaluator.go
internal/app/tfsec/parser/load_module.go
internal/app/tfsec/parser/load_module_metadata.go
internal/app/tfsec/parser/parser.go
internal/app/tfsec/scanner/scanner.go

Modules are now loaded relative to the base project directory, including for nested modules.

Tweak nested module loading

---

internal/app/tfsec/checks/azu008.go
internal/app/tfsec/test/azu008_test.go

Private cluster enabled AZU008

---

internal/app/tfsec/checks/gen003.go

Whitelist secret_name on github_actions_organization_secret

---

Dockerfile

Signed-off-by: Pujan Shah <pujan14@gmail.com>
Switch to go 1.15 for build container

Switch to go 1.15 for build container

---

go.sum

- run `go mod tidy` with go1.15.8

chore: update go.sum

---

internal/app/tfsec/parser/attribute.go
internal/app/tfsec/parser/attribute_test.go

Support for more than one tag. Test added. Test also added for safety for absence of tag.

Reopen of issues 552

---

Dockerfile.ci
README.md
scripts/publish-image.sh

Add tfsec/tfsec-ci for use in CI build
- doesn't specify the entrypoint so can be overridden with a command
Resolves #539

owen ci build

---

example/main.tf
internal/app/tfsec/checks/aws038.go
internal/app/tfsec/checks/aws050.go
internal/app/tfsec/checks/aws052.go
internal/app/tfsec/checks/aws053.go
internal/app/tfsec/checks/aws054.go
internal/app/tfsec/checks/aws055.go
internal/app/tfsec/checks/aws057.go
internal/app/tfsec/checks/aws058.go
internal/app/tfsec/checks/aws059.go
internal/app/tfsec/checks/aws060.go
internal/app/tfsec/checks/aws061.go
internal/app/tfsec/checks/aws062.go
internal/app/tfsec/checks/aws063.go
internal/app/tfsec/checks/aws064.go
internal/app/tfsec/checks/aws065.go
internal/app/tfsec/checks/aws066.go
internal/app/tfsec/checks/aws067.go
internal/app/tfsec/checks/aws068.go
internal/app/tfsec/checks/aws069.go
internal/app/tfsec/checks/azu015.go
internal/app/tfsec/test/aws063_test.go
internal/app/tfsec/test/aws064_test.go
internal/app/tfsec/test/aws065_test.go
internal/app/tfsec/test/aws066_test.go
internal/app/tfsec/test/aws067_test.go
internal/app/tfsec/test/aws068_test.go
internal/app/tfsec/test/aws069_test.go

Update some checks to use attribute blocks in the result

Add some new checks and go back to update some

---

internal/app/tfsec/parser/evaluator.go

- tweak performance with a set for blocks
- fixing the mereg mechanism
tackling #625

tackling performance hit loading large nested modules

---

internal/app/tfsec/custom/processing.go

Fix regex match for custom check

---

internal/app/tfsec/checks/azu020.go
internal/app/tfsec/test/azu020_test.go

add check for network acl on azure key vault

---

.pre-commit-hooks.yaml

Added pre-commit hooks to use the projects docker image or using tcsec binary already on the system (in case they do not have golang installed but do have the binary).

added additional precommit hooks

---

internal/app/tfsec/checks/aws024.go

Correct interpolation for kms_key_id

---

internal/app/tfsec/parser/evaluator.go
internal/app/tfsec/parser/load_module.go
internal/app/tfsec/parser/parser.go

Fix issue where the same module is repeatedly processed for a seemingly infinite loop
Resolve #674

Fix #674 with infinite loop

---

internal/app/tfsec/scanner/scanner.go

if an attribute range is present in the block but no ignore specified, move to the line above the block to check for ignores
Resolves #680

Handle ignores at the top of the block

---

internal/app/tfsec/checks/azu022.go
internal/app/tfsec/checks/azu023.go
internal/app/tfsec/checks/azu024.go
internal/app/tfsec/checks/azu025.go
internal/app/tfsec/test/azu023_test.go
internal/app/tfsec/test/azu024_test.go
internal/app/tfsec/test/azu025_test.go

AZU022 – Changed Error to Warning. 
AZU023 - Key Vault Secret should have an expiration date set. Resoves #285
AZU024 - RDP access should not be accessible from the Internet, should be blocked on port 3389. resolves #268
AZU025 - Data Factory should have public access disabled.

Edited Error Type for AZ022, Added AZ023, AZ024 & AZ025

---

internal/app/tfsec/parser/attribute.go
internal/app/tfsec/parser/attribute_test.go

Handle boolean strings like "false" and "true"
Add supporting tests

tweak boolean helpers

---

docs-website/docs/config/custom_checks.md

Fixes #711 , apparently this was already possible

document using "provider" as a type

---

.github/workflows/build.yml
.github/workflows/doc_release.yml
.github/workflows/tfsec.yml
Makefile
cmd/tfsec-pr-lint/linter.go
cmd/tfsec-pr-lint/main.go
internal/app/tfsec/formatters/default.go
internal/app/tfsec/scanner/check.go
internal/app/tfsec/scanner/result.go

Now we have impact and resolution we can add to the default output to give more information on steps to perform and why

Add the impact and resolution to default

---

internal/app/tfsec/checks/aws089.go

Following https://github.com/tfsec/tfsec/issues/737, I create this PR.

Update name of AWS089

---

internal/app/tfsec/test/aws044_test.go

tests to understand what is happening with #726 and variables

Adding additional AWS044 tests

---

internal/app/tfsec/checks/aws069.go

correct documentation for AWS069

---

.goreleaser.yml

i- also, only sign the checksums file
Closes #749

Fix the version for built tfsec

---

internal/app/tfsec/rules/aws089.go

Correct the documentation

---

internal/app/tfsec/rules/gen001.go

fix issue with non-returning check

---

internal/app/tfsec/block/attribute.go

- a common custom use case is checking for a specific value in a tag,
this will allow the tag key/value pair to be passed
comfortably handle string, number, boolean
Resolve #774

Handle map values in the contains function

---

.github/workflows/release.yml
.goreleaser.yml

- Support tags for release candidates
- release only the tagged version on prerelease
Resolve issues raised in #778

support prerelease

---

internal/app/tfsec/scanner/scanner.go

`--include-passed` doesn't work now.
```
$ tfsec --include-passed /path/to/tf
```

Fix --include-passed

---

internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/formatters/default.go
internal/app/tfsec/parser/evaluator.go
internal/app/tfsec/scanner/scanner.go

@owenrumney I've left the checks you mentioned and the custom check code, as well as the `funcs` package brought across from the terraform internals.

Reduce cyclomatic complexity

---

internal/app/tfsec/block/block.go
internal/app/tfsec/block/hclblock.go
internal/app/tfsec/custom/processing.go
internal/app/tfsec/rules/aws004.go
internal/app/tfsec/rules/aws014.go

- add GetAttribute to do nested attributes

Fix some cyclo issues

---

internal/app/tfsec/rules/gen003.go
internal/app/tfsec/test/gen003_test.go

Fix type check in GEN003

---

cmd/tfsec-pr-lint/linter.go
cmd/tfsec-pr-lint/main.go
internal/app/tfsec/rules/aws046.go

correct the issue in AWS046 where no links supplied

Fix issue with exit code for linter

---

internal/app/tfsec/rules/gen001.go
internal/app/tfsec/rules/gen002.go
internal/app/tfsec/test/gen001_test.go

Check type is string and the value is resolvable for GEN002

---

internal/app/tfsec/block/attribute.go
internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/rules/aws097.go
internal/app/tfsec/test/aws097_test.go

Allow KMS actions for all resources for non-IAM policy documents

---

internal/app/tfsec/rules/aws098.go
internal/app/tfsec/test/aws098_test.go

Add check for aws_s3_bucket_public_access_block per s3 bucket

---

README.md
cmd/tfsec/main.go
internal/app/tfsec/updater/updater.go
version/version.go

Improve version output for local builds

---

cmd/tfsec-skeleton/generate.go
cmd/tfsec-skeleton/templates.go
internal/app/tfsec/rules/dig001.go
internal/app/tfsec/rules/dig002.go
internal/app/tfsec/test/dig001_test.go
internal/app/tfsec/test/dig002_test.go
pkg/provider/provider.go
scripts/publish-docs.sh

- add support for docs for Oracle and Digital Ocean

Add the initial checks for digital ocean

---

internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/rules/dig004.go
internal/app/tfsec/rules/dig005.go
internal/app/tfsec/test/dig004_test.go
internal/app/tfsec/test/dig005_test.go

- Add a rule for digital ocean load balancer
- Add a rule for public read AC:
- add rule and tests for loadbalancer
- fix cyclo issues caused by refactoring hclattribute

Add more checks for Digital Ocean

---

cmd/tfsec-skeleton/templates.go
internal/app/tfsec/rules/dig004.go
internal/app/tfsec/rules/dig005.go
internal/app/tfsec/rules/dig006.go
internal/app/tfsec/rules/dig007.go
internal/app/tfsec/test/dig006_test.go
internal/app/tfsec/test/dig007_test.go

- check force_destroy isn't activated on bucket
- check that versioning is enabled
- update the template for new checks
- correct default severity

Add more checks for digital ocean spaces

---

cmd/tfsec-docs/checks.go
cmd/tfsec-docs/webpage.go

Tidy up the documentation template

---

internal/app/tfsec/rules/gcp001.go
internal/app/tfsec/rules/gcp013.go
internal/app/tfsec/test/gcp001_test.go
internal/app/tfsec/test/gcp013_test.go

Rework GCP-001 (and add new raw_key check)

---

.vscode/launch.json
example/custom_functions/.tfsec/functions_tfchecks.yaml
example/custom_functions/main.tf
internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/block/value_functions.go

- support passing a function into the mapvalue of Contains function

Add custom map value function

---

README.md
SIGNING.md
internal/app/tfsec/rules/dig007.go

Removing the empty link from dig007

Add the signing verification instructions

---

internal/app/tfsec/block/attribute.go
internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/rules/aws097.go
internal/app/tfsec/rules/aws099.go
internal/app/tfsec/scanner/scanner.go
internal/app/tfsec/test/aws099_test.go
pkg/severity/severity.go

Add check for AWS IAM policy best practice

---

.goreleaser.yml
.pre-commit-hooks.yaml

Fix the release

---

internal/app/tfsec/formatters/default.go
internal/app/tfsec/metrics/metrics.go
internal/app/tfsec/scanner/scanner.go

Break down counts by severity in default formatter

---

internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/test/count_test.go
pkg/rule/check.go

Fix 'count==0' resources giving false positives

---

cmd/tfsec/main.go
example/counts/main.tf
internal/app/tfsec/block/block.go
internal/app/tfsec/block/hclblock.go
internal/app/tfsec/parser/evaluator.go
internal/app/tfsec/test/count_test.go
pkg/result/result.go
pkg/rule/check.go

Add full support for count

---

README.md

Removing badge until https://github.com/badges/shields/issues/6766 is fixed.

Removing downloads badge

---

.goreleaser.yml

also remove signing of checksums file

Remove the check gen artefact from goreleaser

---

example/custom_functions/.tfsec/functions_tfchecks.yaml
example/custom_functions/main.tf
internal/app/tfsec/block/value_functions.go
internal/app/tfsec/rules/gen005.go

add support for regexMatches on the map value function. This is to
support matching things like tags to ensure that they follow a certain
pattern.

Add regex value function

---

cmd/tfsec/main.go
internal/app/tfsec/block/hclblock.go
internal/app/tfsec/rules/aws099.go
internal/app/tfsec/scanner/scanner.go
internal/app/tfsec/test/aws099_test.go

inspector resources can be wildcarded
also fix the metrics for deduplicated results
Resolves #888

Support inspector having wide access to resources

---

cmd/tfsec-skeleton/generate.go
cmd/tfsec-skeleton/templates.go

- Update the skeleton generator

v1 skeleton update

---

internal/app/tfsec/rules/google/storage/enable_uniform_bucket_level_access.go
internal/app/tfsec/rules/google/storage/enable_uniform_bucket_level_access_test.go
internal/app/tfsec/rules/init.go
pkg/result/result.go

Ensure that Cloud Storage buckets have uniform bucket-level access enabled

---

cmd/tfsec-docs/webpage.go
internal/app/tfsec/formatters/default.go

Update the documentation to write the legacy file and the new one

Add the legacy ID to default results

---

cmd/tfsec-docs/checks.go

tidy up the table for the checks §

change the formatting of the home pages

---

.vscode/launch.json
cmd/tfsec/main.go
example/moduleWithIgnore/main.tf
example/workspace/main.tf
internal/app/tfsec/parser/evaluator.go
internal/app/tfsec/parser/option.go
internal/app/tfsec/parser/parser.go
internal/app/tfsec/scanner/option.go
internal/app/tfsec/scanner/scanner.go
internal/app/tfsec/test/ignore_test.go
internal/app/tfsec/testutil/util.go

Pass the --workspace argument at runtime
ignores should include #tfsec:ignore:AWS006:ws:workspaceName
Resolves #907

Add support for the workspace ignores

---

internal/app/tfsec/rules/aws/eks/no_public_cluster_access_to_cidr_rule.go
internal/app/tfsec/rules/aws/eks/no_public_cluster_access_to_cidr_rule_test.go

Fix EKS check for public access CIDR

---

Makefile
go.mod
go.sum
internal/app/tfsec/rules/azure/compute/no_secrets_in_custom_data_rule.go
internal/app/tfsec/rules/azure/compute/no_secrets_in_custom_data_rule_test.go
internal/app/tfsec/rules/general/secrets/sensitive_in_attribute_value_rule.go
internal/app/tfsec/rules/general/secrets/sensitive_in_attribute_value_rule_test.go
vendor/github.com/owenrumney/squealer/pkg/config/default.go
vendor/modules.txt

- Add check for secrets in the azurerm_virtual_machine
- Add check for sensitive in azure VM

2144 azurerm virtual machine

---

internal/app/tfsec/rules/azure/compute/disable_password_authentication_rule.go
internal/app/tfsec/rules/azure/compute/disable_password_authentication_rule_test.go

check if password authentication is disabled and raise error if not

Add check for azure vm password auth

---

internal/app/tfsec/block/hclblock.go

Support for_each with unknown iterator values

---

cmd/tfsec-skeleton/generate.go
cmd/tfsec-skeleton/templates.go
internal/app/tfsec/rules/azure/securitycenter/alert_on_severe_notifications_rule.go
internal/app/tfsec/rules/azure/securitycenter/alert_on_severe_notifications_rule_test.go
internal/app/tfsec/rules/azure/securitycenter/enable_standard_subscription_rule.go
internal/app/tfsec/rules/azure/securitycenter/set_required_contact_details_rule.go
internal/app/tfsec/rules/azure/securitycenter/set_required_contact_details_rule_test.go

update generator to support hyphenated services

Add check for security contact phone

---

internal/app/tfsec/rules/google/sql/pg_log_checkpoints_rule.go
internal/app/tfsec/rules/google/sql/pg_log_checkpoints_rule_test.go
internal/app/tfsec/rules/google/sql/pg_log_connections_rule.go
internal/app/tfsec/rules/google/sql/pg_log_connections_rule_test.go
internal/app/tfsec/rules/google/sql/pg_log_disconnections_rule.go
internal/app/tfsec/rules/google/sql/pg_log_disconnections_rule_test.go
internal/app/tfsec/rules/google/sql/pg_log_errors_rule.go
internal/app/tfsec/rules/google/sql/pg_log_errors_rule_test.go
internal/app/tfsec/rules/google/sql/pg_log_lock_waits_rule.go
internal/app/tfsec/rules/google/sql/pg_log_lock_waits_rule_test.go
internal/app/tfsec/rules/google/sql/pg_no_min_statement_logging_rule.go
internal/app/tfsec/rules/google/sql/pg_no_min_statement_logging_rule_test.go

- Add check for google sql checkpoint logging
- Add check for google sql connection logging
- Add check for google sql disconnection logging
- Add check for google sql postgres lock wait logging
- Add check for google sql postgres lock wait logging
- Add google sql postgres min duration statements check
- Add postgres minimum log severity check

Add multiple Google Cloud SQL Postgres checks

---

internal/app/tfsec/scanner/scanner.go

Fix issue with windows line endings

---

cmd/tfsec-docs/webpage.go
internal/app/tfsec/rules/azure/database/enable_ssl_enforcement_rule.go
internal/app/tfsec/rules/azure/database/enable_ssl_enforcement_rule_test.go
internal/app/tfsec/rules/azure/database/no_public_access_rule.go
internal/app/tfsec/rules/azure/database/no_public_access_rule_test.go
internal/app/tfsec/rules/azure/database/secure_tls_policy_rule.go
internal/app/tfsec/rules/azure/database/secure_tls_policy_rule_test.go

- ssl enforcement
- no public access
- minimum tls

Add checks for azure databases

---

internal/app/tfsec/rules/azure/database/no_public_firewall_access_rule.go
internal/app/tfsec/rules/azure/database/no_public_firewall_access_rule_test.go

if start is 0.0.0.0 and end isn't the same, raise an error

Add check for azure sql firewall

---

internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/rules/aws/iam/block_kms_policy_wildcard_rule.go
internal/app/tfsec/rules/aws/iam/block_kms_policy_wildcard_rule_test.go
internal/app/tfsec/rules/aws/iam/no_policy_wildcards_rule.go
internal/app/tfsec/rules/aws/iam/no_policy_wildcards_rule_test.go
internal/app/tfsec/rules/azure/monitor/activity_log_retention_set_rule.go
internal/app/tfsec/rules/azure/monitor/activity_log_retention_set_rule_test.go
internal/app/tfsec/rules/azure/monitor/capture_all_activities_rule.go
internal/app/tfsec/rules/azure/monitor/capture_all_activities_rule_test.go
internal/app/tfsec/rules/azure/monitor/capture_all_regions_rule.go
internal/app/tfsec/rules/azure/monitor/capture_all_regions_rule_test.go
internal/app/tfsec/rules/init.go
internal/app/tfsec/test/attribute_test.go

fixes to the Contains helper function

adding checks for azure activity logging

---

example/counts/main.tf
internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/test/count_test.go
internal/app/tfsec/testutil/util.go

add supporting test
Resolves #962

handle traverseIndex when checking reference

---

cmd/tfsec-docs/navigation_docs.go

add usage permenantly to the navigation doc

Add usage doc

---

internal/app/tfsec/formatters/default.go

I think this makes the output a bit clearer to the user

Move ignored checks with other severities

---

README.md

See https://github.com/aquasecurity/tfsec/issues/987#issuecomment-891237194

docs: Clarify ignore functionality

---

internal/app/tfsec/block/reference.go
internal/app/tfsec/hclcontext/context.go
internal/app/tfsec/rules/aws/s3/specify_public_access_block_rule_test.go

Reference checking now follows foreach

---

cmd/tfsec/main.go
cmd/tfsec/main_test.go
example/1000/.tfsec/custom_tfchecks.json
example/1000/main.tf
internal/app/tfsec/custom/custom_check.go
internal/app/tfsec/custom/processing.go
internal/app/tfsec/custom/processing_test.go

- Add notEqual action for custom check
- Fix the and predicate check to return true only if all are true
Resolves #1000

Add support for preConditions in custom checks

---

.github/workflows/tfsec.yml

Reverts aquasecurity/tfsec#1005

Revert "Update tfsec.yml"

---

CONTRIBUTING.md

Fix slack link for contributing

---

internal/app/tfsec/rules/google/gke/node_pool_uses_cos_rule.go

correct required image_type

---

internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/rules/aws/documentdb/enable_log_export_rule.go

support list is the isAny helper

---

internal/app/tfsec/rules/azure/storage/default_action_deny_rule.go
internal/app/tfsec/rules/azure/storage/default_action_deny_rule_test.go

Check for corresponding network rules block

---

cmd/tfsec/main.go
internal/app/tfsec/custom/processing_test.go
internal/app/tfsec/scanner/option.go
internal/app/tfsec/test/module_test.go
internal/app/tfsec/test/performance_test.go
internal/app/tfsec/test/scanner_test.go
internal/app/tfsec/testutil/util.go
pkg/rule/check.go

@skirkpatrick tests for a panic on rule checking
This rework uses the tests provided by @skirkpatrick but moves the nil protection into the check.
Also reworking StopOnErrors to be more intuitive

Slight rework of the nil protection

---

internal/app/tfsec/rules/general/secrets/sensitive_in_attribute_rule.go

Add whitelist for Private Key Type

---

cmd/tfsec/main.go

alert when trying to run tfsec against a file

---

cmd/tfsec/main.go
pkg/severity/severity.go

Resolves #1149
- sort severity from critical to none
- add conversion of Severity to Int

Add --sort-severity option

---

internal/app/tfsec/rules/google/kms/rotate_kms_keys_rule.go

Fix issue with EKM using in GCP Key

---

internal/app/tfsec/block/hclattribute.go

Fix handling of internal panic when calling terraform hcl functions on null values

---

internal/app/tfsec/test/ignore_test.go
pkg/result/ignores.go

- ignore must be on the resource, inline not supported
- add tests
Resolves #1119

Add support for allowed values in ignores

---

Dockerfile
Dockerfile.ci
Dockerfile.scratch
internal/app/tfsec/scanner/scanner.go
pkg/result/result.go
pkg/result/set.go
pkg/rule/check.go

- pending the move to defsec ensure service is on results

Add Result Service

---

cmd/tfsec/main.go
internal/app/tfsec/parser/option.go
internal/app/tfsec/parser/parser.go

- pass --exclude-path multiple times with relative paths to exclude
Resolves #1168

Add support for --exclude-path

---

internal/app/tfsec/rules/google/compute/enable_vpc_flow_logs_rule.go

Fix the gcp enable flow logs check

---

docs/checks/aws/elb/drop-invalid-headers.md

Fix typo in docs drop-invalid-headers

---

internal/app/tfsec/adapter/kubernetes/adapt.go
internal/app/tfsec/rules/kubernetes/network/no_public_egress_rule.go
internal/app/tfsec/rules/kubernetes/network/no_public_ingress_rule.go

closes: https://github.com/aquasecurity/tfsec/issues/1196

Kubernetes - convert tfsec checks to use defsec logic

---

internal/app/tfsec/adapter/azure/datalake/adapt.go
internal/app/tfsec/rules/azure/datalake/enable_at_rest_encryption_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1208

Azure datalake - convert to use defsec

---

internal/app/tfsec/adapter/openstack/adapt.go
internal/app/tfsec/rules/openstack/compute/no_plaintext_password_rule.go
internal/app/tfsec/rules/openstack/compute/no_public_access_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1200

Openstack - convert to use defsec logic

---

internal/app/tfsec/adapter/digitalocean/compute/adapt.go
internal/app/tfsec/block/hclattribute.go
internal/app/tfsec/rules/digitalocean/compute/use_ssh_keys_rule.go
internal/app/tfsec/rules/digitalocean/compute/use_ssh_keys_rule_test.go

There was a typo in the test code, and an unnamed test which fails with my changes. I'm not really sure how to fix it. I can work a bit more with the `digitalocean` checks.
`empty data for ssh key fails` is the problematic one. Help on how to fix is appreciated :100:

DigitalOcean SSH keys check

---

internal/app/tfsec/block/type.go
internal/app/tfsec/parser/evaluator.go
internal/app/tfsec/parser/parser_test.go
internal/app/tfsec/schema/schema.go

Fix to add support for the new moved blocks
see https://github.com/aquasecurity/tfsec/issues/1192

add support for moved blocks tf 1.1.0+

---

internal/app/tfsec/adapter/azure/appservice/adapt.go
internal/app/tfsec/rules/azure/appservice/account_identity_registered_rule.go
internal/app/tfsec/rules/azure/appservice/authentication_enabled_rule.go
internal/app/tfsec/rules/azure/appservice/enable_http2_rule.go
internal/app/tfsec/rules/azure/appservice/enforce_https_rule.go
internal/app/tfsec/rules/azure/appservice/require_client_cert_rule.go
internal/app/tfsec/rules/azure/appservice/use_secure_tls_policy_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1235

Azure app service - convert to use defsec

---

internal/app/tfsec/adapter/azure/authorization/adapt.go
internal/app/tfsec/rules/azure/authorization/limit_role_actions_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1229

Azure authorization - adapt to use defsec

---

internal/app/tfsec/adapter/azure/synapse/adapt.go
internal/app/tfsec/rules/azure/synapse/virtual_network_enabled_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1227

Azure synapse - convert to use defsec

---

internal/app/tfsec/adapter/azure/monitor/adapt.go
internal/app/tfsec/rules/azure/monitor/activity_log_retention_set_rule.go
internal/app/tfsec/rules/azure/monitor/capture_all_activities_rule.go
internal/app/tfsec/rules/azure/monitor/capture_all_regions_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1225

Azure monitor - convert to use defsec logic

---

internal/app/tfsec/adapter/azure/securitycenter/adapt.go
internal/app/tfsec/rules/azure/securitycenter/alert_on_severe_notifications_rule.go
internal/app/tfsec/rules/azure/securitycenter/enable_standard_subscription_rule.go
internal/app/tfsec/rules/azure/securitycenter/set_required_contact_details_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1217

Azure security center - convert to use defsec

---

internal/app/tfsec/adapter/azure/datafactory/adapt.go
internal/app/tfsec/rules/azure/datafactory/no_public_access_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1215

Azure data factory - adapt to use defsec

---

internal/app/tfsec/adapter/cloudstack/compute/adapt.go
internal/app/tfsec/rules/cloudstack/compute/no_sensitive_info_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1213

Cloudstack compute - adapt to use defsec

---

README.md

I found missing links.
Please review 🙏

Fix missing links

---

internal/app/tfsec/adapter/github/repositories/adapt.go
internal/app/tfsec/rules/github/repositories/private_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1202

Github repositories - convert to use defsec

---

go.mod
go.sum
internal/app/tfsec/adapter/oracle/adapt.go
internal/app/tfsec/rules/oracle/compute/no_public_ip_rule.go
vendor/github.com/aquasecurity/defsec/rules/oracle/compute/no_public_ip.go
vendor/modules.txt

Closes: https://github.com/aquasecurity/tfsec/issues/1203

Oracle compute - adapt to use defsec

---

docs/checks/azure/database/retention-period-set.md
internal/app/tfsec/rules/azure/database/retention_period_set_rule.go
internal/app/tfsec/rules/azure/database/retention_period_set_rule_test.go

Fixes #1240
Depends on this https://github.com/aquasecurity/defsec/pull/52
Not sure if the documentation should be updated as well https://github.com/aquasecurity/tfsec/blob/master/docs/checks/azure/database/retention-period-set.md

Add support for unlimited retention policy for azurerm_sql_server

---

internal/app/tfsec/adapter/google/dns/adapt.go
internal/app/tfsec/rules/google/dns/enable_dnssec_rule.go
internal/app/tfsec/rules/google/dns/no_rsa_sha1_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1252

Google DNS - adapt to use defsec

---

internal/app/tfsec/adapter/google/kms/adapt.go
internal/app/tfsec/rules/google/kms/rotate_kms_keys_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1250

Google KMS - adapt to use defsec

---

internal/app/tfsec/adapter/google/bigquery/adapt.go
internal/app/tfsec/rules/google/bigquery/no_public_access_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1248

Google big query - adapt to use defsec

---

internal/app/tfsec/rules/general/secrets/sensitive_in_attribute_rule.go
internal/app/tfsec/rules/general/secrets/sensitive_in_attribute_rule_test.go

Remove false positive in vault pki

---

cmd/tfsec/main.go
docs/getting-started/usage.md
internal/app/tfsec/ignores/migration.go

- Add migration for ignores
- Update the usage documentation

add migrate ignores option

---

internal/app/tfsec/adapter/aws/cloudtrail/adapt.go
internal/app/tfsec/rules/aws/cloudtrail/enable_all_regions_rule.go
internal/app/tfsec/rules/aws/cloudtrail/enable_at_rest_encryption_rule.go
internal/app/tfsec/rules/aws/cloudtrail/enable_log_validation_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1265

AWS CloudTrail - update to use defsec

---

internal/app/tfsec/adapter/aws/cloudwatch/adapt.go
internal/app/tfsec/rules/aws/cloudwatch/log_group_customer_key_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1267

AWS CloudWatch - adapt to use defsec

---

internal/app/tfsec/adapter/aws/ebs/adapt.go
internal/app/tfsec/rules/aws/ebs/enable_volume_encryption_rule.go
internal/app/tfsec/rules/aws/ebs/encryption_customer_key_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1275

AWS EBS - adapt to use defsec

---

internal/app/tfsec/adapter/aws/efs/adapt.go
internal/app/tfsec/rules/aws/efs/enable_at_rest_encryption_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1277

AWS EFS - adapt to use defsec

---

internal/app/tfsec/adapter/aws/kinesis/adapt.go
internal/app/tfsec/rules/aws/kinesis/enable_in_transit_encryption_rule.go

Closes https://github.com/aquasecurity/tfsec/issues/1279

AWS Kinesis - adapt to use defsec

---

internal/app/tfsec/adapter/aws/codebuild/adapt.go
internal/app/tfsec/rules/aws/codebuild/enable_encryption_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1271

AWS Codebuild - adapt to use defsec

---

internal/app/tfsec/adapter/aws/elb/adapt.go
internal/app/tfsec/rules/aws/elb/drop_invalid_headers_rule.go
internal/app/tfsec/rules/aws/elb/use_secure_tls_policy_rule.go
internal/app/tfsec/rules/aws/elb/use_secure_tls_policy_rule_test.go

Closes #1293 
Create load balancers adapter
Add `"aws_alb"` resource to the examples

AWS ELB - adapt to use defsec

---

internal/app/tfsec/adapter/aws/config/adapt.go
internal/app/tfsec/rules/aws/config/aggregate_all_regions_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1273

AWS Config - adapt to use defsec

---

internal/app/tfsec/adapter/aws/redshift/adapt.go
internal/app/tfsec/rules/aws/redshift/encryption_customer_key_rule.go
internal/app/tfsec/rules/aws/redshift/non_default_vpc_deployment_rule.go

AWS Redshift - adapt to use defsec

---

internal/app/tfsec/adapter/aws/mq/adapt.go
internal/app/tfsec/rules/aws/mq/enable_audit_logging_rule.go
internal/app/tfsec/rules/aws/mq/enable_general_logging_rule.go
internal/app/tfsec/rules/aws/mq/no_public_access_rule.go

AWS MQ - adapt to use defsec

---

internal/app/tfsec/adapter/aws/elasticache/adapt.go
internal/app/tfsec/rules/aws/elasticache/add_description_for_security_group_rule.go
internal/app/tfsec/rules/aws/elasticache/enable_backup_retention_rule.go
internal/app/tfsec/rules/aws/elasticache/enable_in_transit_encryption_rule.go
internal/app/tfsec/rules/aws/elasticache/encrypt_replication_group_rule.go

AWS Elasticache - adapt to use defsec

---

internal/app/tfsec/adapter/aws/neptune/adapt.go
internal/app/tfsec/rules/aws/neptune/enable_log_export_rule.go
internal/app/tfsec/rules/aws/neptune/enable_storage_encryption_rule.go

AWS Neptune - adapt to use defsec

---

internal/app/tfsec/adapter/aws/autoscaling/adapt.go
internal/app/tfsec/rules/aws/autoscaling/enable_at_rest_encryption_rule.go
internal/app/tfsec/rules/aws/autoscaling/no_public_ip_rule.go
internal/app/tfsec/rules/aws/autoscaling/no_sensitive_info_rule.go

Closes: https://github.com/aquasecurity/tfsec/issues/1269

AWS Autoscaling - convert to use defsec

---

pkg/externalscan/external_scan.go

when using the external scanner only load the custom checks once

Only load custom checks once

---

internal/app/tfsec/adapter/aws/workspaces/adapt.go
internal/app/tfsec/rules/aws/workspaces/enable_disk_encryption_rule.go

AWS Workspaces - adapt to use defsec

---

internal/app/tfsec/rules/general/secrets/sensitive_in_attribute_rule.go
internal/app/tfsec/rules/general/secrets/sensitive_in_attribute_rule_test.go

Whitelist kubernetes_service_account token

---

internal/app/tfsec/adapter/aws/sqs/adapt.go
internal/app/tfsec/rules/aws/sqs/enable_queue_encryption_rule.go
internal/app/tfsec/rules/aws/sqs/no_wildcards_in_policy_documents_rule.go
internal/app/tfsec/rules/aws/sqs/no_wildcards_in_policy_documents_rule_test.go

AWS SQS adapt to use defsec

---

internal/app/tfsec/adapter/aws/kms/adapt.go
internal/app/tfsec/rules/aws/kms/auto_rotate_keys_rule.go

AWS KMS - adapt to use defsec

---

internal/app/tfsec/adapter/aws/documentdb/adapt.go
internal/app/tfsec/rules/aws/documentdb/enable_log_export_rule.go
internal/app/tfsec/rules/aws/documentdb/enable_storage_encryption_rule.go
internal/app/tfsec/rules/aws/documentdb/encryption_customer_key_rule.go

AWS DocDB - adapt to use defsec

---

internal/app/tfsec/adapter/aws/ssm/adapt.go
internal/app/tfsec/rules/aws/ssm/secret_use_customer_key_rule.go
internal/app/tfsec/rules/aws/ssm/secret_use_customer_key_rule_test.go

AWS SSM adapt to use defsec

---

internal/app/tfsec/adapter/aws/ecr/adapt.go
internal/app/tfsec/rules/aws/ecr/enable_image_scans_rule.go
internal/app/tfsec/rules/aws/ecr/enforce_immutable_repository_rule.go
internal/app/tfsec/rules/aws/ecr/no_public_access_rule.go
internal/app/tfsec/rules/aws/ecr/repository_customer_key_rule.go

AWS ECR - adapt to use defsec

---

go.mod
go.sum
internal/app/tfsec/adapter/azure/database/adapt.go
internal/app/tfsec/rules/azure/database/all_threat_alerts_enabled_rule.go
internal/app/tfsec/rules/azure/database/enable_audit_rule.go
internal/app/tfsec/rules/azure/database/enable_ssl_enforcement_rule.go
internal/app/tfsec/rules/azure/database/no_public_access_rule.go
internal/app/tfsec/rules/azure/database/no_public_firewall_access_rule.go
internal/app/tfsec/rules/azure/database/no_public_firewall_access_rule_test.go
internal/app/tfsec/rules/azure/database/postgres_configuration_log_checkpoints_rule.go
internal/app/tfsec/rules/azure/database/postgres_configuration_log_connection_throttling_rule.go
internal/app/tfsec/rules/azure/database/postgres_configuration_log_connections_rule.go
internal/app/tfsec/rules/azure/database/retention_period_set_rule.go
internal/app/tfsec/rules/azure/database/retention_period_set_rule_test.go
internal/app/tfsec/rules/azure/database/secure_tls_policy_rule.go
internal/app/tfsec/rules/azure/database/threat_alert_email_set_rule.go
internal/app/tfsec/rules/azure/database/threat_alert_email_to_owner_rule.go
vendor/github.com/aquasecurity/defsec/cidr/cidr.go
vendor/github.com/aquasecurity/defsec/rules/azure/database/secure_tls_policy.go
vendor/github.com/aquasecurity/defsec/rules/azure/network/disable_rdp_from_internet.go
vendor/github.com/aquasecurity/defsec/rules/azure/network/ssh_blocked_from_internet.go
vendor/github.com/aquasecurity/defsec/rules/google/compute/use_secure_tls_policy.go
vendor/github.com/aquasecurity/defsec/types/reference.go
vendor/modules.txt

Added server and database resources in examples/tests (when required).
Closes #1238

Azure database adapt to use defsec

---

docs/getting-started/usage.md

Fix gif flag in docs

---

internal/app/tfsec/adapter/aws/msk/adapt.go
internal/app/tfsec/rules/aws/msk/enable_in_transit_encryption_rule.go
internal/app/tfsec/rules/aws/msk/enable_logging_rule.go

AWS MSK adapt to use defsec

---

internal/app/tfsec/custom/processing.go
internal/app/tfsec/custom/processing_test.go

- also added checks for regexMatches custom checks
fixes #1300

fix issue where custom check regexMatches action wasn't being handled correctly

---

internal/app/tfsec/adapter/google/gke/adapt.go
internal/app/tfsec/rules/google/gke/enable_auto_repair_rule.go
internal/app/tfsec/rules/google/gke/enable_auto_upgrade_rule.go
internal/app/tfsec/rules/google/gke/enable_ip_aliasing_rule.go
internal/app/tfsec/rules/google/gke/enable_master_networks_rule.go
internal/app/tfsec/rules/google/gke/enable_network_policy_rule.go
internal/app/tfsec/rules/google/gke/enable_private_cluster_rule.go
internal/app/tfsec/rules/google/gke/enable_stackdriver_logging_rule.go
internal/app/tfsec/rules/google/gke/enable_stackdriver_monitoring_rule.go
internal/app/tfsec/rules/google/gke/enforce_pod_security_policy_rule.go
internal/app/tfsec/rules/google/gke/enforce_pod_security_policy_rule_test.go
internal/app/tfsec/rules/google/gke/metadata_endpoints_disabled_rule.go
internal/app/tfsec/rules/google/gke/no_legacy_auth_rule.go
internal/app/tfsec/rules/google/gke/no_public_control_plane_rule.go
internal/app/tfsec/rules/google/gke/node_metadata_security_rule.go
internal/app/tfsec/rules/google/gke/node_metadata_security_rule_test.go
internal/app/tfsec/rules/google/gke/node_pool_uses_cos_rule.go
internal/app/tfsec/rules/google/gke/node_shielding_enabled_rule.go
internal/app/tfsec/rules/google/gke/node_shielding_enabled_rule_test.go
internal/app/tfsec/rules/google/gke/use_cluster_labels_rule.go
internal/app/tfsec/rules/google/gke/use_rbac_permissions_rule.go
internal/app/tfsec/rules/google/gke/use_rbac_permissions_rule_test.go
internal/app/tfsec/rules/google/gke/use_service_account_rule.go
internal/app/tfsec/rules/google/gke/use_service_account_rule_test.go

Google GKE adapt to use defsec

---

go.mod
go.sum
internal/app/tfsec/adapter/azure/keyvault/adapt.go
internal/app/tfsec/rules/azure/keyvault/content_type_for_secret_rule.go
internal/app/tfsec/rules/azure/keyvault/content_type_for_secret_rule_test.go
internal/app/tfsec/rules/azure/keyvault/ensure_key_expiry_rule.go
internal/app/tfsec/rules/azure/keyvault/ensure_key_expiry_rule_test.go
internal/app/tfsec/rules/azure/keyvault/ensure_secret_expiry_rule.go
internal/app/tfsec/rules/azure/keyvault/ensure_secret_expiry_rule_test.go
internal/app/tfsec/rules/azure/keyvault/no_purge_rule.go
internal/app/tfsec/rules/azure/keyvault/specify_network_acl_rule.go
vendor/github.com/aquasecurity/defsec/provider/azure/keyvault/keyvault.go
vendor/github.com/aquasecurity/defsec/rules/azure/keyvault/no_purge.go
vendor/github.com/aquasecurity/defsec/types/time_value.go
vendor/modules.txt

Azure keyvault defsec

---

go.mod
go.sum
internal/app/tfsec/adapter/google/sql/adapt.go
internal/app/tfsec/rules/google/sql/enable_backup_rule.go
internal/app/tfsec/rules/google/sql/enable_pg_temp_file_logging_rule.go
internal/app/tfsec/rules/google/sql/encrypt_in_transit_data_rule.go
internal/app/tfsec/rules/google/sql/mysql_no_local_infile_rule.go
internal/app/tfsec/rules/google/sql/no_contained_db_auth_rule.go
internal/app/tfsec/rules/google/sql/no_cross_db_ownership_chaining_rule.go
internal/app/tfsec/rules/google/sql/no_public_access_rule.go
internal/app/tfsec/rules/google/sql/no_public_access_rule_test.go
internal/app/tfsec/rules/google/sql/pg_log_checkpoints_rule.go
internal/app/tfsec/rules/google/sql/pg_log_connections_rule.go
internal/app/tfsec/rules/google/sql/pg_log_disconnections_rule.go
internal/app/tfsec/rules/google/sql/pg_log_errors_rule.go
internal/app/tfsec/rules/google/sql/pg_log_lock_waits_rule.go
internal/app/tfsec/rules/google/sql/pg_no_min_statement_logging_rule.go
vendor/github.com/aquasecurity/defsec/provider/google/iam/iam.go
vendor/github.com/aquasecurity/defsec/provider/google/sql/sql.go
vendor/modules.txt

Google SQL adapt to use defsec

---

internal/app/tfsec/cmd/output.go

Only add extension when multiple formats are specified, preserving pre-v1 behaviour

---

internal/app/tfsec/cmd/output.go

Prevent extra output when writing to file

---

internal/app/tfsec/cmd/output.go

Fix doc links for RC

---

internal/pkg/adapter/aws/elasticsearch/adapt.go

Fixes issue #1399 with elastic search domain logging

---

internal/pkg/scanner/pool.go

Fix rerunning defsec rules again for multiple modules

---

.github/workflows/build.yml
.github/workflows/golangci-lint.yml

- chore: Skip CI on markdown pages
- fix typo

chore: fix ci

---

internal/app/tfsec/cmd/output.go

fix: fix doc link

---

docs/checks/aws/autoscaling/enforce-http-token-imds.md
docs/checks/aws/autoscaling/no-secrets-in-user-data.md
docs/checks/aws/ec2/enable-at-rest-encryption.md
example/workspace/main.tf
go.mod
go.sum
internal/pkg/adapter/aws/autoscaling/adapt.go
internal/pkg/adapter/aws/ec2/adapt.go
mkdocs.yml
vendor/github.com/aquasecurity/defsec/provider/aws/autoscaling/autoscaling.go
vendor/github.com/aquasecurity/defsec/provider/aws/ec2/instance.go
vendor/github.com/aquasecurity/defsec/rules/aws/ec2/enable_at_rest_encryption.cf.go
vendor/github.com/aquasecurity/defsec/rules/aws/ec2/enable_at_rest_encryption.go
vendor/github.com/aquasecurity/defsec/rules/aws/ec2/enable_at_rest_encryption.tf.go
vendor/modules.txt

Move instance checks into ec2 so they're not showing up as autoscaling
Resolves #1433

fix: correct autoscaling duplication for instances

---

go.mod
go.sum
vendor/github.com/zclconf/go-cty/cty/convert/conversion.go
vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go
vendor/github.com/zclconf/go-cty/cty/convert/unify.go
vendor/github.com/zclconf/go-cty/cty/function/function.go
vendor/github.com/zclconf/go-cty/cty/function/stdlib/collection.go
vendor/github.com/zclconf/go-cty/cty/function/stdlib/csv.go
vendor/github.com/zclconf/go-cty/cty/function/stdlib/format.go
vendor/github.com/zclconf/go-cty/cty/function/stdlib/number.go
vendor/github.com/zclconf/go-cty/cty/function/stdlib/sequence.go
vendor/github.com/zclconf/go-cty/cty/marks.go
vendor/github.com/zclconf/go-cty/cty/primitive_type.go
vendor/github.com/zclconf/go-cty/cty/type.go
vendor/github.com/zclconf/go-cty/cty/value_init.go
vendor/github.com/zclconf/go-cty/cty/value_ops.go
vendor/github.com/zclconf/go-cty/cty/walk.go
vendor/modules.txt

fix: Downgrade zclconf/go-cty to match hcl package version and fix panic

---

go.mod
go.sum
vendor/github.com/aquasecurity/defsec/provider/aws/iam/wildcards.go
vendor/github.com/aquasecurity/defsec/rules/aws/iam/no_policy_wildcards.go
vendor/github.com/aquasecurity/defsec/rules/aws/sam/no_function_policy_wildcards.go
vendor/modules.txt

feat: Combine AWS IAM wildcards in same statement

---

internal/pkg/adapter/google/kms/adapt.go

fix: check that the rotation value is set before casting to string"

---

internal/pkg/adapter/google/kms/adapt.go

fix: Add metadata to google keyring

---

docs/getting-started/configuration/custom-checks.md
internal/pkg/custom/custom_check.go

docs: document preConditions in custom checks

---

internal/pkg/block/attribute.go

Resolves #1479 
Resolves #1484

fix: Handle go-cty value derive panics

---

rules.md

fix(rules): I needed to ignore this rule in my project to get an exception on one of my Terraform variables

fix: updated rules.md with missing rule

---

go.mod
go.sum
internal/pkg/adapter/aws/s3/bucket.go
vendor/github.com/aquasecurity/defsec/rules/aws/neptune/enable_storage_encryption.tf.go
vendor/github.com/aquasecurity/defsec/rules/aws/s3/enable_bucket_encryption.go
vendor/github.com/aquasecurity/defsec/rules/aws/s3/encryption_customer_key.cf.go
vendor/github.com/aquasecurity/defsec/rules/aws/s3/encryption_customer_key.go
vendor/github.com/aquasecurity/defsec/rules/aws/s3/encryption_customer_key.tf.go
vendor/modules.txt

feat: separate s3 encryption into 2 checks

---

internal/pkg/block/ignore.go
internal/pkg/block/modules.go
internal/pkg/parser/evaluator.go
internal/pkg/parser/load_blocks.go
internal/pkg/scanner/scanner.go
test/ignore_test.go

fix: Fix regression of missing parameterised ignore rules

---

docs/getting-started/configuration/custom-checks.md
internal/pkg/custom/complex_checks.go
internal/pkg/custom/custom_check.go
internal/pkg/custom/processing.go
internal/pkg/custom/processing_test.go

- added subMatchOne attribute
- added tests, and docs
solves #1437

feat: add subMatchOne attribute to custom checks checking for one match only

---

internal/pkg/block/attribute.go

fix: string slices can now be correctly passed by variable

---

internal/pkg/block/sort.go
internal/pkg/parser/evaluator.go
test/deterministic_test.go

fix: Make results deterministic by expanding for_each and count in hierarchical order

---

docs/checks/aws/neptune/enable-storage-encryption.md
docs/checks/aws/neptune/encryption-customer-key.md
docs/checks/aws/s3/encryption-customer-key.md
docs/checks/aws/s3/no-public-access-with-acl.md
docs/checks/google/gke/enable-ip-aliasing.md
docs/checks/google/gke/enable-master-networks.md
docs/checks/google/gke/no-public-control-plane.md
go.mod
go.sum
internal/pkg/adapter/azure/keyvault/adapt.go
mkdocs.yml
vendor/github.com/aquasecurity/defsec/rules/aws/s3/no_public_access_with_acl.go
vendor/modules.txt

fix: Azure KeyVault Secrets: use RFC3339 to parse expiry time

---

internal/app/tfsec/cmd/output.go

fix: tfsec output links for custom checks

---

example/custom/.tfsec/custom_tfchecks.yaml
internal/pkg/custom/processing.go

feat: support include passed for custom checks

---

internal/pkg/block/block.go

When the block is part of a top level resource [resource, module, data etc] then it may have a keyword block name, eg; resource.
When this happens, there is an assumption that there will be labels which there aren't - see #1528 for an example
Resolves #1528
example it fixes
```hcl
resource "kubernetes_horizontal_pod_autoscaler" "app" {
depends_on = [helm_release.replicated]
metadata {
name = "app-hpa"
namespace = coalesce([for i, v in data.kubernetes_all_namespaces.allns.namespaces : try(regexall("replicated\\-.*", v)[0], "")]...)
}
spec {
min_replicas = 2
max_replicas = 10
scale_target_ref {
kind        = "Deployment"
name        = "app-deployment"
api_version = "apps/v1"
}
metric {
type = "Resource"
resource {
name = "memory"
target {
type                = "Utilization" …
```

fix: handle special case child blocks

---

go.mod
go.sum

fix: Panic on google iam resource scanning

---

go.mod
go.sum
pkg/scanner/scanner.go

fix: support symlinks in the parser

---

.github/workflows/build.yml
.github/workflows/golangci-lint.yml
Makefile
go.mod
go.sum
internal/pkg/ignores/migration.go

fix: Update defsec to v0.13.1 to fix azurerm config block parsing

---

.github/workflows/build.yml
Makefile
internal/app/tfsec/cmd/flags.go
pkg/scanner/options.go

fix: Fix regression with --exclude-path

---

go.mod
go.sum
pkg/scanner/scanner.go

fix: update to latest defsec to load files deterministically

---

go.mod
go.sum

fix: regression on archived repository fix

---

_examples/archived/main.tf
go.mod
go.sum

bring in the latest defsec which fixes the issue of archive status not being captured
Resolves #1572

fix: archive not being picked up on github

---

go.mod
go.sum

fix: Run all filter functions via defsec

---

go.mod
go.sum

fix: Load embedded files correctly on Windows

---

go.mod
go.sum
internal/app/tfsec/cmd/flags.go
internal/pkg/legacy/map.go

fix: Fix race condition in legacy ignore rule matching

---

_examples/1607/.tfsec/custom_tfchecks.yaml
_examples/1607/main.tf
internal/pkg/custom/loader.go

fix: fix custom check validator

---

.github/workflows/release.yml
Makefile

chore: don't create the tfsec/tfsec images any more

---

internal/app/tfsec/cmd/root.go

fix: min version checking

---

go.mod
go.sum

chore(defsec): fix permissions for downloaded modules

---

.golangci.yml
go.mod
go.sum

fix(defsec): Update defsec to v0.31.0 to fix multiple missing metadata issues

---

go.mod
go.sum

fix: Fix Windows build

---

internal/pkg/config/config.go
test/flags_test.go
test/testdata/config-minimum-severity/config.yml

fix(config): Fix minimum_severity in yaml config files

---

go.mod
go.sum

chore(defsec): Update defsec to v0.34.0

---

go.mod
go.sum
test/testdata/rego/policies/rego.rego

fix(rego): Fix code highlighting for rego detections

---

go.mod
go.sum

feat(defsec): Add support for applying rego rules to IAM policies

---

go.mod
go.sum

chore(deps): bump defsec version

---

.github/workflows/test.yml
go.mod
go.sum

fix(parsing): Symlink resolution fix

---

_examples/1693/main.tf
docs/guides/rego/rego.md
go.mod
go.sum
test/testdata/rego/policies/rego.rego

fix(ignores): handle parameter based ignores in a foreach

---

go.mod
go.sum

fix: Update defsec to fix unknown value error in reference

---

internal/app/tfsec/cmd/flags.go

feat: add glob support to exclude paths

---

go.mod
go.sum

chore(deps): bump defsec

---

Dockerfile
_examples/1775/main.tf

fix: add git to Docker file so it can download modules

---

.github/workflows/mkdocs-latest.yaml
Makefile
docs/requirements.txt
go.mod
go.sum

fix: Fix module handling via update to defsec v0.65.0

---

internal/pkg/formatter/html.go
internal/pkg/formatter/markdown.go

feat: Improve markdown/html output

---

go.mod
go.sum

chore: Update defsec to v0.68.2

---

go.mod
go.sum

fix: fix public block linking

---

go.mod
go.sum

fix: Fix bad use of AsNumber

---

docs/checks/aws/lambda/enable-tracing/index.md

I found a very tiny typo in the document.

fix tiny typo

---

go.mod
go.sum

Bring in the Alias usage in ignores to Resolve #1842

chore: bump defsec

---

README.md
install_linux.sh
scripts/install_linux.sh

add a script to allow easy installation directly from bash

automate the installation of tfsec on linux

---

go.mod
go.sum

Resolves #1841
Resolves #1863 
Resolves #1864

fix: Fix s3 public access block linking

---

go.mod
go.sum

Resolves https://github.com/aquasecurity/tfsec/issues/1862

fix: panic in sqs adapter

---

docs/guides/configuration/ignores.md

As mentioned in https://github.com/aquasecurity/tfsec/issues/493#issuecomment-1231889681

docs: Add module ignore documentation

---

scripts/install_linux.sh

To avoid TOCTOU and other security issues, use `mktemp` to create a download directory for tfsec and checksum. Remove all usage of `/tmp` entirely.

fix: Use `mktemp` instead of `/tmp` to securely manage temporary directories

---

docs/guides/configuration/custom-checks.md
internal/pkg/custom/custom_check.go
internal/pkg/custom/processing.go

feat: support optional provider and service name in custom checks

---

_examples/cidrblocks/.tfsec/custom_tfchecks.yaml
_examples/cidrblocks/main.tf
docs/guides/configuration/custom-checks.md
go.mod
go.sum
internal/pkg/custom/custom_check.go
internal/pkg/custom/processing.go

- feat: support optional provider and service name in custom checks
- docs: add missing required type in docs
- feat: support onlyContains in custom checks
Alos Resolves #1901

feat: support onlyContains custom check matchspec

---

cmd/tfsec-checkgen/main.go
go.mod
internal/app/tfsec/cmd/flags.go
internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/custom/loader.go
internal/pkg/ignores/migration.go

Signed-off-by: Simar <simar@linux.com>

bump go to version 1.19

---

docs/index.md
tfsec-to-trivy-migration-guide.md

Related to the tasks in the following issue #2016

docs: Trivy callout and migration guide added 

---

cmd/tfsec/main.go

Fixes: https://github.com/aquasecurity/tfsec/issues/2066

feat: Add a transition message
