- Dockerfile
- README.md
This commit includes the introduction of a Dockerfile so that the user
may build a Docker image containing tfsec so that it may be run without
having to install it on the host system.
To build:
```sh
docker build -t tfsec .
```
To run:
```sh
docker run --rm -it -v "$(pwd):/workdir" tfsec .
```
> Add Dockerfile for Docker support

- README.md
- go.mod
- internal/app/tfsec/checks/gke_abac_enabled.go
- internal/app/tfsec/gke_abac_enabled_test.go
Adds a GKE check that ensures that legacy abac is disabled.
> In Kubernetes, RBAC is used to grant permissions to resources at the cluster and namespace level. RBAC allows you to define roles with rules containing a set of permissions. RBAC has significant security advantages and is now stable in Kubernetes, so it’s time to disable ABAC.
https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#leave_abac_disabled_default_for_110
> [GKE check] Add check for legacy abac (attribute-based access control)

- README.md
- internal/app/tfsec/aws_unencrypted_cloudfront_communications_test.go
- internal/app/tfsec/checks/aws_unencrypted_cloudfront_communications.go
**Background:** 
CloudFront distributions can serve content over HTTP or HTTPS. The protocol to use is defined in the `viewer_protocol_policy` argument  found in `default_cache_behavior` and in the optional `ordered_cache_behavior` arguments.
This alerts on:
1. `default_cache_behavior` not being defined
2. `viewer_protocol_policy` within `default_cache_behavior` not being defined
3. `viewer_protocol_policy` set to `allow-all` which allows HTTP and HTTPS communications
If `ordered_cache_behavior` arguments are found then it alerts on:
1. `viewer_protocol_policy` not being defined in any `ordered_cache_behavior`'s
2. `viewer_protocol_policy` set to `allow-all` in any `ordered_cache_behavior`'s
**Note**: 
[`viewer_protocol_policy`](https://www.terraform.io/docs/providers/aws/r/cloudfront_dist …
> add check for unencrypted cloudfront comms

- README.md
- internal/app/tfsec/aws_cloudfront_outdated_protocol_test.go
- internal/app/tfsec/checks/aws_cloudfront_outdated_protocol.go
Checks for outdated SSL/TLS usage. 
**Background**
CloudFront supports a few different protocols and ciphers for communication between viewers and CloudFront. The supported security policies from CloudFront are are:
- SSLv3
- TLSv1
- TLSv1_2016
- TLSv1.1_2016
- TLSv1.2_2018
From a best practice perspective [AWS says](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html) 
> We recommend that you specify TLSv1.2_2018 unless your viewers are using browsers or devices that don’t support TLSv1.2. 
This adds a check for that.
> Adds check for outdated SSL/TLS usage in cloudfront

- README.md
- internal/app/tfsec/aws_unencrypted_msk_broker_transit_test.go
- internal/app/tfsec/checks/aws_unencrypted_msk_broker_transit.go
Add check for plaintext communication for MSK clusters.
Using code AWS022 as AWS021 is used in https://github.com/liamg/tfsec/pull/80
> Add check for msk unencrypted data in transit

- README.md
- cmd/tfsec/main.go
- internal/app/tfsec/formatters/junit.go
This PR adds support for the JUNIT format used in the CircleCI and few other projects. 
This is how it looks now in the CirlcleCI: 
If you have CircleCI account you can see build (from the branch tfsec-demo) here: https://app.circleci.com/pipelines/github/samm-git/tfsec/4/workflows/9eccc711-dbd1-4d6b-b324-152f5c416094/jobs/4
This should also address https://github.com/liamg/tfsec/issues/85, but i do not have jenkins to test
> Add junit support

- README.md
Hello,
I found your tool recently and I totally loved it. As I use terraform regularly, I thought it would be nice to have such a tool as a security checker when someone does a PR on our repos.
This is why I'd like to propose to add a line to reference my action in your README, such that people who want to do the same as me, have already a way to do it and do not struggle to develop it.
Of course, as I'm only reusing your tool, I'm totally open to adapt my version if you think there is something wrong.
Thanks for your time and your tool.
Tom
> Add optional action to run `tfsec` on a repository

- internal/app/tfsec/parser/parser.go
- internal/app/tfsec/parser/parser_test.go
This fixes #52 . The details on the thread were immensely helpful for identifying the issues here.
There were two separate bugs:
1. We were not correctly setting the filepath for all local module references. The `source` for modules was working only when the path pointed to a sibling or child directory (a common use-case). However, if it referenced a parent directory, this would break the parsing directory traversal logic.
2. As we didn't pass any state to the recursive parsing, this opened up the potential for an infinite loop. A situation that could cause this is the following directory structure:
```
/my-module
fileA
fileB
examples/
simple/
main.tf // <--- where source = "../.."
```
This PR addresses the first issue by determining when we've set the wrong path and correcting it. It …
> fix: defend against infinite traversal for local modules

- .gitignore
- README.md
- cmd/tfsec/main.go
- internal/app/tfsec/module_scan_test.go
- internal/app/tfsec/scanner/scanner.go
- internal/app/tfsec/setup_test.go
Hi Liam,
please consider my PR to add new argument to disable/ignore provided checks globally in whole project. Idea is to turn off/skip checks which generate False Positive findings for particular repository
Possible scenarios where this can help:
1. GEN003 finds issues in standard K8S secret manager resources
2. Disable other unused Cloud Providers
Thanks
> Added new arguments to exclude some checks globaly

- cmd/tfsec/main.go
Hello, 
We'd like to run tfsec in CI without breaking the build. This PR adds the --soft-fail flag to ensure that the exit code always returns `0`. Reports are otherwise unchanged.
> add soft-fail flag

- cmd/tfsec/main.go
The --help shows an extra quote
```
--no-color         Disable colored output (American style!)
--no-colour        Disable coloured output
-s, --soft-fail        'Runs checks but suppresses error code
```
> Remove extra quote in the help text

- internal/app/tfsec/formatters/junit.go
Bitbucket requires to know the number of tests and failures in order to pick up the test report.
Related to #85 and #112
> Add number of failures (and tests) to testsuite

- README.md
- internal/app/tfsec/checks/gke_enforce_psp.go
- internal/app/tfsec/checks/gke_legacy_auth_enabled.go
- internal/app/tfsec/checks/gke_legacy_metadata_endpoints.go
- internal/app/tfsec/checks/gke_node_metadata_exposed.go
- internal/app/tfsec/checks/gke_shielded_nodes_disabled.go
- internal/app/tfsec/gke_enforce_psp_test.go
- internal/app/tfsec/gke_legacy_auth_enabled_test.go
- internal/app/tfsec/gke_legacy_metadata_endpoints_test.go
- internal/app/tfsec/gke_node_metadata_exposed_test.go
- internal/app/tfsec/gke_shielded_nodes_disabled_test.go
👋 
Thought I'd add some more GKE security checks. I'll do my best to implement any feedback! If this gets added I can create some wiki pages for these rules to provide more context.
- GCP006: Checks if `node_metadata` in `workload_metadata_config` is set to `EXPOSE` or `UNSPECIFIED`
> setting the flag to EXPOSED or UNSPECIFIED disables metadata concealment.
https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#create-concealed
- GCP007: Checks if legacy metadata endpoints have been disabled
> Compute Engine's instance metadata server exposes legacy /0.1/ and /v1beta1/ endpoints, which do not enforce metadata query headers.
https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#disable-legacy-apis
- GCP008: Checks for use of risky …
> [GKE Checks] Add additional security checks for k8s

- internal/app/tfsec/aws_cloudfront_outdated_protocol_test.go
- internal/app/tfsec/checks/aws_cloudfront_outdated_protocol.go
AWS recommends CloudFront security policy version **TLSv1.2_2019**.
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html
P.S. Thank you for your great tool!
P.S. I found another PR https://github.com/liamg/tfsec/pull/153 after creating this PR, but I am also modifying the test code, so please review it once.
Resolves https://github.com/liamg/tfsec/issues/152
> CloudFront recommended Security Policy version is TLSv1.2_2019

- README.md
- internal/app/tfsec/aws_outdated_tls_policy_elasticsearch_domain_endpoint_test.go
- internal/app/tfsec/aws_plaintext_node_to_node_elasticsearch_traffic_test.go
- internal/app/tfsec/aws_unencrypted_elasticearch_domain_test.go
- internal/app/tfsec/aws_unenforced_https_elasticsearch_domain_endpoint_test.go
- internal/app/tfsec/checks/aws_oudated_tls_policy_elasticsearch_domain_endpoint.go
- internal/app/tfsec/checks/aws_plaintext_node_to_node_elasticsearch_traffic.go
- internal/app/tfsec/checks/aws_unencrypted_elasticsearch_domain.go
- internal/app/tfsec/checks/aws_unenforced_https_elasticsearch_domain_endpoint.go
This PR adds a few new AWS checks for a few best practices on Elasticsearch domains. I'd love for these to be included, let me know your thoughts @liamg! Specifically, it checks for the these blocks:
```hcl
encrypt_at_rest {
enabled = true
}
``` 
```hcl
node_to_node_encryption {
enabled = true
}
```
```hcl
domain_endpoint_options {
enforce_https = true
}
```
> feat: add check for encryption at rest for Elasticsearch domains

- README.md
- internal/app/tfsec/aws_unencrypted_at_rest_elasticache_replication_group_test.go
- internal/app/tfsec/aws_unencrypted_in_transit_elasticache_replication_group_test.go
- internal/app/tfsec/checks/aws_unencrypted_at_rest_elasticache_replication_group.go
- internal/app/tfsec/checks/aws_unencrypted_in_transit_elasticache_replication_group.go
- internal/app/tfsec/checks/utils.go
- internal/app/tfsec/checks/utils_test.go
This PR adds checks for ensuring that encryption at rest and encryption in transit are set for Elasticache Replication Groups.
> feat: add checks for encryption at rest and in transit for Elasticache

- README.md
- internal/app/tfsec/checks/google_user_iam_grant.go
- internal/app/tfsec/google_user_iam_grant_test.go
👋 Adding another GCP check that looks for IAM grants directly to user identities. It searches data types `google_iam_policy` and quite a few resource types related to IAM to accomplish this. All it searches for is a prefix of `user:` within the member/members attribute of each block.
Example TF blocks it would flag:
```
data "google_iam_policy" "test-policy" {
binding {
...
members = [
"group:test@example.com",
"user:test@example.com",
]
}
}
resource "google_storage_bucket_iam_binding" "bucket-binding" {
...
members = [
"user:test@example.com",
]
}
resource "google_project_iam_member" "project-member" {
...
member = "user:test@example.com"
}
```
If I've forgotten any resources from the check feel free to add them. Otherwise once this gets merged I'll put together a documentation page 👍
> [GCP Check] Add IAM user grant check

- internal/app/tfsec/checks/aws047.go
- internal/app/tfsec/test/aws047_test.go
A new check for AWS to check for wildcard actions defined in
`aws_sqs_queue_policy` resources.
Fixes #274
> Add AWS SQS policy wildcard action check

- internal/app/tfsec/checks/aws018.go
- internal/app/tfsec/test/aws018_test.go
Added explanation, examples and reference links to _AWS018_ `AWSNoDescriptionInSecurityGroup` check. Added the  examples to the test as well.
Renamed the 3 documentation constants to match the scanner constants above.
Relates to #269 (actual check is already implemented here)
> Add documentation for AWS018

- internal/app/tfsec/checks/aws006.go
The message in `AWS006` (`AWSOpenIngressSecurityGroupRule`) in the IPv6
cidr section mentions an *egress* rule, though it actually checks for an
*ingress* rule.
> Fix AWS006 message for IPv6 CIDR

- README.md
README link is missing, so link to https://www.tfsec.dev
P.S. congrats new website! Thanks!
> fix: README link tfsec.dev

- internal/app/tfsec/checks/aws006.go
- internal/app/tfsec/checks/aws007.go
- internal/app/tfsec/checks/aws008.go
- internal/app/tfsec/checks/aws009.go
- internal/app/tfsec/checks/azu001.go
- internal/app/tfsec/checks/azu002.go
- internal/app/tfsec/checks/gcp003.go
- internal/app/tfsec/checks/gcp004.go
- internal/app/tfsec/checks/utils.go
- internal/app/tfsec/checks/utils_test.go
Extracted the repeated open CIDR checks into a separate utility function.
I realize this was "_unasked for_" and "_not discussed yet_" according to the contributing guide, though I figured it's the only way to move forward with even more of these checks planned.
Consider this a proposal, and open for discussion.
I'm not sure what to do with the similar checks for *azure*, as in that case, there also seems to be `"*"` possible as an open CIDR.
> Extract open cidr checks into util function

- internal/app/tfsec/formatters/sarif.go
- missing the full path to the link
> Update the help link for the sarif report

- docs-website/_docs/github_security_alerts.md
Hi!
[As per the docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow) the default GITHUB_TOKEN variable is uppercase.
I also noticed in the [github_security_alerts](https://www.tfsec.dev/docs/github_security_alerts/) page the example is not being rendered correct: 
```
github_token: $
```
If I recall correctly prepending a `$` in front of the expression should prevent it being evaluated when the docs are being generated.
Stephen
> Fix github_token -> GITHUB_TOKEN

- internal/app/tfsec/checks/azu010.go
- internal/app/tfsec/test/azu010_test.go
Created rule AZ010 to verify if the flag enable_https_traffic_only is enabled in the Terraform Resource azurerm_storage_account. If this flag is not set, it will be automatically be set to true, so I added a nil check on the attribute.
Documentation:
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account
- https://docs.microsoft.com/en-us/azure/storage/blobs/security-recommendations
- https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview
> Azure Storage Account HTTPS enabled rule created

- internal/app/tfsec/checks/gcp012.go
- internal/app/tfsec/test/gcp012_test.go
👋 
Just adding a check to ensure that `service_account` is overridden in `google_container_cluster` and `google_container_node_pool` inside the `node_config` block.
* GCP012: Checks if `node_config` in `google_container_cluster` or `google_container_node_pool` has a service account defined which is recommended by Google (see below)
Reference: https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#use_least_privilege_sa
> By default, nodes are given the Compute Engine default service account, which you can find by navigating to the IAM section of the Cloud Console. This account has broad access by default, making it useful to wide variety of applications, but it has more permissions than are required to run your Kubernetes Engine cluster. **You should create and use …
> Add GCP check to ensure that GKE node service accounts are overridden

- internal/app/tfsec/checks/gcp012.go
- internal/app/tfsec/test/gcp012_test.go
Looking at the [docs for `google_container_cluster` and `node_config`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_config), it says the `node_config` block shouldn't be used together with `google_container_node_pool`.  So, we probably don’t need to flag this check if the `node_config` is not defined in the `google_container_cluster` block since its likely they are not using the default node pool.
> Don't raise check if `node_config` is empty on `google_container_cluster`

- cmd/tfsec/main.go
Formatter output set to lowercase, supporting uppercase and lowercase output types (CSV, JSON, csv, json etc.)
> Set format output to support uppercase & lowercase 

- internal/app/tfsec/formatters/default.go
- internal/app/tfsec/formatters/junit.go
- internal/app/tfsec/formatters/sarif.go
- internal/app/tfsec/formatters/text.go
- internal/app/tfsec/scanner/check.go
👋 Here's a quick PR that updates check output to account for custom checks. This changes the output based on provider so custom checks point to relatedLinks instead of `https://tfsec.dev/docs/custom/CUS001`.
It would be worthwhile to make sure you're happy with how the output is handled for the various other formats (ie: json, csv, checkstyle, junit, sarif). Feel free to tweak this! I just thought I'd put a PR in for this quick fix so custom checks aren't sent to a 404 😄
> Support related link output for custom checks

- internal/app/tfsec/parser/attribute.go
- internal/app/tfsec/test/aws053_test.go
Addresses https://github.com/tfsec/tfsec/issues/506
Fixes issues in the `IsEmpty` when the value is unresolvable for any reason. `IsEmpty` ensures that there are some literal components.
This is a bit of mitigation - the issue mentioned by @gluehbirnenkopf seems to be slightly different from @calvinrodo in that Calvin is concatenating up the KMS value using parts while @gluehbirnenkopf looks like it is a case of using a var that doesn't have a default value. This could be resolved using `--tfvars-file terraform.tfvars` and passing vars for testing purposes
> Add additional test to verify AWS053

- README.md
Link for tfsec-example-project points to gighub.com (not github) and a project that doesn't exist.
This MR fixes the broken link. :smile:
> Fix broken link to tfsec-example-project

- internal/app/tfsec/checks/gcp011.go
- internal/app/tfsec/checks/gcp012.go
- internal/app/tfsec/checks/gen003.go
- internal/app/tfsec/parser/attribute.go
- internal/app/tfsec/test/gcp011_test.go
- internal/app/tfsec/test/gcp012_test.go
- internal/app/tfsec/test/gen003_test.go
I tried using tfsec for our GCP projects and had many false positives. This is addressing some of them:
- Adding `google_secret_manager_secret` to whitelist of GEN003. This resource will not contain secrets but the `secret_id` is likely to be named with a sensitive attribute (e.g. secret or token) since this is a secret manager after all!
- GCP011 was failing with error when the identities in the members attribute were unknowns. 
- GCP012 was creating false positive when the `service_account` was using a reference expression.
> Fixing false positives with rules related to GCP

- internal/app/tfsec/checks/gen003.go
- internal/app/tfsec/test/gen003_test.go
In one of my projects, I use the [GitHub Provider](https://www.terraform.io/docs/providers/github/index.html) to manage GitHub repository secrets (that can be used inside GitHub Action Workflows), like:
```hcl
resource "github_actions_secret" "infrastructure_digitalocean_deploy_user" {
repository      = "infrastructure"
secret_name     = "digitalocean_deploy_user"
plaintext_value = var.digitalocean_deploy_user
}
```
Running tfsec at the moment leads to
```
Problem 27
[GEN003][WARNING] Block 'module.github:github_actions_secret.infrastructure_digitalocean_deploy_user' includes a potentially sensitive attribute which is defined within the project.
/infrastructure/infrastructure/github/action_secret.tf:201
198 | // User to be used to execute this deploy
199 | resource "github_actions_secret" …
```
> GEN003: Add support for github_actions_secret.secret_name by whitelisting

- Dockerfile
- scripts/build.sh
Fixes #538
It looks like the change in #520 stopped the version number being set in the docker image, as it introduced multiple `-ldflags` arguments to the `go build` command, of which there can only be one. If there are multiple `-ldflags` then the last one takes precedence. The docker builds specify the version first, followed by the static linking flags, which is why the docker images didn't have the version number set.
This also updates the build script to use a single `-ldflags` argument, which means the binaries will now be statically linked.
> Fix docker version

- internal/app/tfsec/checks/aws019.go
- internal/app/tfsec/test/aws019_test.go
This should allow folks to avoid ignoring cases they can do nothing about.
> AWS KMS key rotation not available for SIGN_VERIFY keys

- internal/app/tfsec/formatters/junit.go
Our users are not as familiar with the RuleIDs
and the description tends to contain a good hint about
what to do next.
> Add the description to the JUnit output.

- scripts/publish-image.sh
Resolves #541 
When tagging a patch version like v0.36.15, also tag a minor version pointing to that patch, eg v0.36. This will allow people to pin to v0.36 and benefit from new checks etc without risking the pinning to latest
> push a minor tag pointing to latest patch

- cmd/tfsec/main.go
Removed redundant assignment of `results` to a `map[scanner.Result]bool{}` without using the `bool` from the `map`
> Simplify removeDuplicatesAndUnwanted()

- .pre-commit-hooks.yaml
Pre-commit (https://pre-commit.com/index.html#intro) is a tool to easily install and run git hooks. By putting this file in the repo, it allows
people to automatically install tfsec with go and run tfsec against every commit.
This requires no additional upkeep on the tfsec project. Pre-commit will simply call go get to install tfsec automatically for anyone.
> added pre-commit hook for tfsec

- cmd/tfsec/main.go
Reverts tfsec/tfsec#564
This doesn't have the desired effect. The .terraform was intended to be included but does present a risk of duplicates.
> Revert "Simplify removeDuplicatesAndUnwanted()"

- cmd/tfsec/main.go
- docs-website/docs/config/config.md
If the default config file is badly formed tfsec will not fail, instead it will continue to dereference a nil tfsecConfig pointer and crash.
To avoid this, first check if the default config file exists, if not we'll continue on happily; otherwise load the config and fail if there are any errors.
> Fix issue when loading a bad default config file 

- internal/app/tfsec/parser/load_module.go
several bugs talk of eternal looping when running against nested module.
This does seem to be a valid fix from the issue.
tested against infrastructure with no performance hit
> Remove key to label check

- internal/app/tfsec/custom/loader.go
To fix a bug that prevents custom check files from using the `.yml` extension.
Golang's switch statements have an implicit auto-break per case. See: https://tour.golang.org/flowcontrol/10
Both `.yml` and `.yaml` extensions are accepted extensions for `YAML` custom check files.  However, the current implementation does not support the `.yml` due to how `switch` statement cases behave in Golang. 
To use the comma-separated list syntax to represent the multiple valid cases for the YAML code path.
(cc: @muplim)
> Add support for the .yml extension in custom check files

- internal/app/tfsec/custom/check_all_statements_test.go
- internal/app/tfsec/custom/processing.go
`subMatch` and `subMatches` originally only looked for the first named block to evaluate.
With resources like IAM policy documents, one can have multiple repetitions of `statement`, making it impossible
to check the second.
I believe this changes the semantics slightly: Every block that could match by name must fulfil the `subMatch`, `subMatches`.  This had no negative impact on our suite. It actually caught a few more policies with potential issues.
Let me know if you feel like this needs some toggle/flag.
> When checking submatches, look for all possible candidate blocks

- docs-website/docs/config/custom_checks.md
- internal/app/tfsec/custom/check_all_statements_test.go
- internal/app/tfsec/custom/custom_check.go
- internal/app/tfsec/custom/loader.go
- internal/app/tfsec/custom/multiple_submatches_test.go
- internal/app/tfsec/custom/processing.go
- internal/app/tfsec/custom/processing_test.go
- internal/app/tfsec/custom/validate.go
Support for `AND` predicates was added as part of https://github.com/tfsec/tfsec/pull/580. 
To re-work the current implementation for composite checks.
The major downsides we found with the current implementation are:
- Some custom checks may benefit from an `or` operator being available.
- The implicit `and` behavior of `subMatches` is not apparent from the check definition files. In consequence, non-experienced users will struggle to understand/write checks without having to refer to the official documentation or rely on their teams' tribal knowledge.
- The `subMatch` / `subMatches` operator is a bit overloaded with too many responsibilities:
-  Provide the ability to “look into” a nested block. 
-  Provide support for `and`-based composite boolean expressions.
To adopt a new …
> Add support for "and" and "or" predicates

- cmd/tfsec/main.go
To introduce `--detailed-exit-code` so that it is possible to know that a `tfsec` run has produced `INFO` messages.
Some CI/CD providers such as `Buildkite` allow expanding each step's logs view as soon as an error occurs. This is an awesome feature as it helps to minimize the log spam noise. 
See: https://buildkite.com/docs/pipelines/managing-log-output#collapsing-output
With the current implementation of `tfsec`, it is impossible to tell whether an execution passed all the checks or it only failed `INFO`-level checks.
This isn't perfect as we believe that `INFO`-level checks should still be reported to the user.
To introduce a new CLI flag (`--detailed-exit-code`) that, when set, produces more informative exit codes to differentiate the following scenarios:
| Exit code       | Execution …
> Adds support for detailed exit code

- internal/app/tfsec/checks/azu017.go
- internal/app/tfsec/test/azu017_test.go
This example below should not trigger `AZU017` warning. PR adds a check to see if the access mode is Deny and doesn't warn in that case.
```
resource "azurerm_network_security_rule" "deny-ssh" {
name                        = "ssh-deny-all"
priority                    = 1000
direction                   = "Inbound"
access                      = "Deny"
protocol                    = "Tcp"
source_port_range           = "*"
destination_port_range      = "22"
source_address_prefix       = "*"
destination_address_prefix  = "*"
resource_group_name         = azurerm_resource_group.example.name
network_security_group_name = azurerm_network_security_group.example.name
}
```
Results in:
```
Problem 1
[AZU017][ERROR] Resource 'azurerm_network_security_rule.deny-ssh' has a . …
```
> AZU017 Should not trigger when access mode is Deny

- internal/app/tfsec/checks/aws051.go
- internal/app/tfsec/test/aws051_test.go
When `aws_rds_cluster` attribute `kms_key_id` was explicitly set to
`null`, tfsec did not catch the disabled encryption and issued a
warning:
> WARNING: skipped AWS051 check due to error(s): value is null
The added test case reproduces this issue.
**Note**: The test case does not _catch_ the issue though, as the test execution
logic seems to differ from the real scanning logic, in that it doesn't
try to format the result.
> Fix AWS051 `value is null` warning

- cmd/tfsec/main.go
- internal/app/tfsec/parser/parser.go
Default action is to search for the first sub directory with a tf file. #634 issue reports that this causes an issue when running from the root of a dir with multiple child locations.
Provide --force-all-dirs argument not search for first tf file and just use the initial folder
Resolves #634
> Add option to not search for tf files

- cmd/tfsec/main.go
- internal/app/tfsec/formatters/checkstyle.go
- internal/app/tfsec/formatters/csv.go
- internal/app/tfsec/formatters/default.go
- internal/app/tfsec/formatters/formatter.go
- internal/app/tfsec/formatters/junit.go
- internal/app/tfsec/formatters/sarif.go
- internal/app/tfsec/formatters/text.go
- internal/app/tfsec/scanner/check.go
- internal/app/tfsec/scanner/result.go
- internal/app/tfsec/scanner/scanner.go
References #623 
Based on feedback to the prior PR (#624), I've made this one less intrusive to the codebase. 
This PR adds an argument (`--include-passed`) that will include all checks that passed against the supplied Terraform.
I've added a `Passed` property on to the `Result` class so that it can be output via the different formatters.  This defaults to `false`.  Since the scanner already does the work of comparing the HCL blocks and checks to find the relevant ones, and then runs the actual check function against the block, I simply had to catch checks that _didn't fail_ their checkFunc (i.e. did not return a `result` object) if the flag was set.
By making the change here, we don't need to have additional conditional logic in each of the formatters or checks themselves to …
> Add argument to include passed checks in the output

- cmd/tfsec/main.go
- example/withVars/main.tf
- example/withVars/terraform.tfvars
Closes #641, provide a warning when a tfvars is available but not being used by tfsec
> Add check for tfvars files and warn if not being used.

- internal/app/tfsec/checks/aws057.go
- internal/app/tfsec/checks/aws070.go
- internal/app/tfsec/test/aws057_test.go
- internal/app/tfsec/test/aws070_test.go
`AWS057` checks if `log_publishing_options` is configured or not which closes  https://github.com/tfsec/tfsec/issues/331
There can be many `log_publishing_options` blocks so we need to check them all.
Checks if any of the `log_publishing_options` has `AUDIT_LOGS`  enabled closes https://github.com/tfsec/tfsec/issues/412
Questions:
- should `AUDIT_LOGS` be a `warning` or `error`?
- should we extend `AWS057` with `AUDIT_LOGS` check?
- this would prevent someone from ignoring only `AUDIT_LOGS` as `tfsec:ignore:AWS057` would ignore both lack of `logs` enabled and `AUDIT_LOGS` missing
> adding aws es domain no logging enabled scanner

- internal/app/tfsec/test/aws004_test.go
I started working on #171 but it turned out it is already covered by older #12 
I noticed the test cases does not validate whether this check is executed against `aws_lb_listener` as well so I added it
The solution to #12 covers #171 and #243 as well
> Added test case for AWS004 check by including the aws_lb_listener

- internal/app/tfsec/checks/aws072.go
- internal/app/tfsec/test/aws072_test.go
This check fails on any appearance of `allow-all` in configuration of `viewer_protocol_policy` in `default_cache_behavior` and all instances of  `ordered_cache_behavior`
I've unit tested this using multiple combinations of `ordered` caches and `default` cache
Closes #180
> Check for Viewer Protocol Policy to be set to HTTPS in Cloudfront Distribution

- scripts/publish-docs.sh
The document https://tfsec.dev/docs/aws/AWS077/ isn't found.
In the build `releasing tfsec`, the document was built but wasn't published.
https://github.com/tfsec/tfsec/runs/2236221933#step:8:129
```
+ echo 'deploying changes'
deploying changes
except don't publish site for pull requests
+ [[ '' != \f\a\l\s\e ]]
+ echo 'except don'\''t publish site for pull requests'
```
https://github.com/tfsec/tfsec/blob/107c86d3c686a3f37b548ef7d704c81cbcd0c0cb/scripts/publish-docs.sh#L16-L19
In #660 , CI was migrated from Travis to GitHub Actions, so we should fix the environment variables of Travis.
`make publish-docs` is run only in GitHub Action's `releasing tfsec`, and this build is run only when tag is pushed.
So we don't have to check the current branch in `make publish-docs`.
> Fix publish-docs to update document

- cmd/tfsec/main.go
- internal/app/tfsec/formatters/default.go
- internal/app/tfsec/metrics/metrics.go
- internal/app/tfsec/scanner/scanner.go
- internal/app/tfsec/test/ignore_test.go
closes  #664
When using `tfsec:ignore` we might forget about these ignores and it would be good to check how many of these are there to make a decision for instance that we have too many ignores in the project.
When checking where are the ignores we could actually try forcing display of them by `tfsec` thus `--include-ignored` flag might be helpful.
When checking where are the ignores we could also check debug logs to check which rules are actually ignored.
> new flag include ignored and counting ignored checks

- go.sum
Hi, I tried to alter the _pre-commit_ hook but didn't manage to get the `go mod tidy` such as performed by goreleaser (https://goreleaser.com/customization/hooks/)
Cheers,
> fix: go.sum cleanup

- internal/app/tfsec/checks/aws079.go
- internal/app/tfsec/test/aws079_test.go
fixes https://github.com/tfsec/tfsec/issues/234
Rules:
- fire if `metadata_options` missing as IMDS v2 is not enforced by default
- fire if `http_tokens` set to `optional` as IMDS v2 is not enforced
- do not fire if `http_tokens` set to `required` as IMDS v2 is enforced
- do not fire if `http_endpoint` set to `disabled` as IMDS is disabled
Docs:
- https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#metadata-options
> new IMDS v2 check

- internal/app/tfsec/checks/aws051.go
- internal/app/tfsec/test/aws051_test.go
allow storage_encrypted to be true and have no KMS_ID specified
Resolves #695
> fix check AWS051

- .github/workflows/build.yml
- Makefile
let's see if this shows the test suite failure mentioned in #719
> chore: bump Go version in GH actions

- README.md
Seems a bit weird why there's a list of official images, but then tell people to use people to use an "unofficial" image (I know a maintainer made it, but the tfsec namespace is better) that hasn't been updated in the last 3 months :)
> [skip ci] Use official Docker image in docker run

- cmd/tfsec/main.go
Trivial change, fixes parameter name in the warning message.
> Use correct parameter name in warning prompt

- internal/app/tfsec/checks/oci001.go
- internal/app/tfsec/test/oci001_test.go
Adding the first Oracle Cloud check, it will check on the use of an IP from the external IP pool versus an IP from the internal IP pool. Warning for the use of publicly routable IPs which could expose a customer service to the public internet.
> adding the first Oracle Cloud check 

- cmd/tfsec/main.go
- cmd/tfsec/main_test.go
solves https://github.com/tfsec/tfsec/issues/739
Added also basic unit tests for `main.go`. This requires further improvements and we should move most of the functions used in `main.go` to new module that is covered by unit tests.
> add in ignore-warnings flag

- internal/app/tfsec/custom/custom_check.go
- internal/app/tfsec/custom/processing.go
- internal/app/tfsec/scanner/context.go
﻿- Custom checks should still have impact
- fix typo in custom check
- Add check action for tag checking
Closes #755 
custom check becomes 
```yaml
---
checks:
- code: CUS001
description: Custom check to ensure the CostCentre tag is applied to EC2 instances
impact: can't track spend
resolution: use the cost centre tag
requiredTypes:
- resource
requiredLabels:
- aws_instance
severity: ERROR
matchSpec:
name: tags
action: hasTag
value: CostCentre
errorMessage: The required CostCentre tag was missing
relatedLinks:
- http://internal.acmecorp.com/standards/aws/tagging.html
``
> add custom check action for tags

- internal/app/tfsec/rules/aws097.go
- internal/app/tfsec/test/aws097_test.go
AWS SecurityHub flags policies that grant permissions
to all possible KMS keys. This falls under the umbrella of "least
privilege" as having such broad permissions would allow an entity
to decrypt data they are not privy to.
> Add a check for IAM policies for KMS

- internal/app/tfsec/scanner/scanner.go
- take the range details from the resource block rather than the result
block
- add a check for someone adding the tfsec ignore in about the result
block
Resolves #781
> The check for ignoring should use the resource block

- cmd/tfsec/main.go
- internal/app/tfsec/formatters/text.go
- internal/app/tfsec/rules/aws006.go
When the --out flag is used with the default or text formatter it has an empty file.
- update text formatter to write to io.Writer
- redirect default formatter to text when a file output is used
Resolves #789
> Allow file output for text

- internal/app/tfsec/rules/aws005.go
- internal/app/tfsec/test/aws005_test.go
the requirement for `internal` does not apply when using a `gateway`
load balancer type
Resolves #795
> Support the load_balancer_type of gateway

- README.md
- internal/app/tfsec/scanner/scanner.go
- internal/app/tfsec/test/ignore_test.go
implements https://github.com/tfsec/tfsec/issues/758
Adds in expiration date for ignore so that when adding ignore I can decide when I should be reminded about check that I am ignoring.
Current format
```
```
> ignore date expiration

- internal/app/tfsec/rules/aws090.go
Scan result description in AWS090 is for containerInsights, not codeInsights.
> fix scan result description in AWS090

- internal/app/tfsec/rules/aws021.go
AWS have just updated their CloudFront TLS policy to drop non-GCM cipher suites. The latest policy is now `TLSv1.2_2021`.
https://aws.amazon.com/about-aws/whats-new/2021/06/amazon-cloudfront-announces-new-tlsv12_2021-security-policy-for-viewer-connections/
> Use the latest TLS policy in AWS021

- internal/app/tfsec/block/attribute.go
- internal/app/tfsec/hclcontext/context.go
- internal/app/tfsec/rules/aws004.go
- internal/app/tfsec/rules/aws016.go
- internal/app/tfsec/rules/aws095.go
- internal/app/tfsec/test/aws004_test.go
- add attribute functions to walk the scope and find the related
resource to a reference so further checks can be performed
- rename `ReferencesDataBlock` to `IsDataBlockReference` to make the intent clearer
> traverse the load balancer to check type

- example/moduleWithIgnore/main.tf
- internal/app/tfsec/block/block.go
- internal/app/tfsec/scanner/scanner.go
when the top-level module has an ignore code above it, any resources in
that module which fails the check will be ignored.
This will include nested modules
Resolve #493
> Support pushdown of module ignores

- .github/workflows/build.yml
- Makefile
- internal/app/tfsec/block/hclattribute.go
- internal/app/tfsec/funcs/crypto.go
- internal/app/tfsec/funcs/string.go
- internal/app/tfsec/rules/aws013.go
- internal/app/tfsec/rules/aws021.go
- internal/app/tfsec/rules/aws025.go
- internal/app/tfsec/rules/aws034.go
- internal/app/tfsec/rules/aws053.go
- internal/app/tfsec/rules/aws086.go
- internal/app/tfsec/rules/aws095.go
- internal/app/tfsec/rules/aws097.go
- internal/app/tfsec/rules/azu014.go
- internal/app/tfsec/rules/dig007.go
- internal/app/tfsec/scanner/scanner.go
- internal/app/tfsec/test/azu003_test.go
- scripts/typos.sh
You can run these locally with `make quality`.
You can also `make typos` to see any typos, and `make fix-typos` to autocorrect them.
> Add gocyclo, vet and misspell to the build process

- example/custom_functions/.tfsec/functions_tfchecks.yaml
- example/custom_functions/main.tf
- internal/app/tfsec/block/hclattribute.go
- internal/app/tfsec/block/value_functions.go
- internal/app/tfsec/config/config.go
- internal/app/tfsec/custom/loader.go
- internal/app/tfsec/custom/validate.go
- pkg/severity/severity.go
custom checks written in json present as map[string]interface{} rather
than the yaml map[interface{}]interface{} so switch needs to cover both
options
should Resolve #784 when custom check is json
> Handle json nested value checks

- internal/app/tfsec/block/hclblock.go
if there is no evalcontext for the block, create a new one
Resolves #882
> handle null evalContext

- internal/app/tfsec/block/block.go
- internal/app/tfsec/block/hclblock.go
- internal/app/tfsec/parser/evaluator.go
- pkg/result/result.go
- check for block expansion only happens once
- Handle same named modules in count
> 882 fix expansion

- scripts/install.sh
install.sh is used by homebrew to build the binary on the fly. fix the reference for setting the version
> fix install script

- cmd/tfsec/main.go
the warning when a tfvars file is found but not used is causing issues
with the github action. Print the error to std.err
Resolves #aquasecurity/tfsec-pr-commenter-action/issues/11
> Print warning to stderr

- example/main.tf
- pkg/result/result.go
The vscode plugin needs the location block on the json results to drive
the treeview - quickest dirtiest way to do it
> Location required on the json results

- cmd/tfsec-docs/extension_codes.go
- cmd/tfsec-docs/main.go
- example/custom/custom_check.tf
- scripts/publish-docs.sh
this will be downloaded by the vscode plugin for ignore resolution
> Create the codes json file during docs build

- .vscode/launch.json
- cmd/tfsec/main.go
- example/with_config_overrides/.tfsec/config.yml
- example/with_config_overrides/main.tf
Severity overrides should support both new code and legacy code in addition to the severity values
Resolves #966
> Support both code and legacy code for config

- internal/app/tfsec/security/sensitive.go
It is used in all the `vault_..._backend_role` resources and being a type, is safe.
E.g. https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/auth_backend#token_type
> feat: Allow `token_type` as a safe attribute

- internal/app/tfsec/rules/aws/documentdb/enable_storage_encryption_rule.go
docdb instance doesn't support the kms id attribute.
Resolves #1019
> Fix issue with documentdb instance kms id

- internal/app/tfsec/rules/aws/vpc/disallow_mixed_sgr_rule.go
- internal/app/tfsec/rules/aws/vpc/disallow_mixed_sgr_rule_test.go
Hello, this adds an AWS check to ensure that usage of security groups with inline rules and security group rule resources are not mixed.
Mixing Terraform standalone `security_group_rule` resource and `security_group` resource with inline ingress/egress rules results in rules being overwritten during Terraform apply. 
This is intended behavior as per [terraform](https://github.com/hashicorp/terraform/issues/11011#issuecomment-283076580) but can result in security group rules being overwritten if one is not careful. Big banner warning from terraform [security group docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group) :
This adds the check in go where we have  access to the `GetReferencedBlock` function. 
I'm not able to express how I can refer to …
> Add check to avoid mixing usage of security_group_rule and security_group with inline rules

- internal/app/tfsec/formatters/default.go
fixes: https://github.com/aquasecurity/tfsec/issues/1037
severityFormat map was initialized before user flags were parsed by main tfsec app. These flags control `tml` parsing. Initialization of severityFormat uses `tml` so it was done with `default` values of tml - by default `no-color` is not set.
Moved severityFormat map generation to `runtime` context within `FormatDefault` function which will use `no-color` flag set by the user.
Added check to only populate this map if its nil.
Example:
```
Result 1
[aws-ecs-enable-container-insight][HIGH] Resource 'aws_ecs_cluster.bad_example' does not have containerInsights enabled
/home/michal-franc/Work/go-src/github.com/michal-franc/tfsec/bin/linux/test.tf:1-3
1 | resource "aws_ecs_cluster" "bad_example" {
2 |   	name = "services-cluster"
3 | }
4 …
```
> fix: no-color for severity

- cmd/tfsec/main.go
I believe this line has been forgotten in https://github.com/aquasecurity/tfsec/pull/1053
Resolves #1055
> fix: do not ignore allExcludedRuleIDs params

- README.md
Links were pointing to a location that required Docker Hub login. Change to public link.
> Update README to fix Docker Hub links

- README.md
The examples in the README still use the old legacy rule identifiers. This pull request changes the legacy rule IDs in the README to their corresponding new, more verbose, rule IDs.
> Use new rule identifiers in README examples

- Dockerfile
- Dockerfile.ci
- Dockerfile.scratch
- would be good practice of specifying the base docker image tag number
- the base image tag dependencies would be managed by dependabot to ensure the latest and greatest
> docker: specify the tags for the dockerfiles

- internal/app/tfsec/rules/aws/cloudfront/use_secure_tls_policy_rule.go
- internal/app/tfsec/rules/aws/cloudfront/use_secure_tls_policy_rule_test.go
> Added cloudfront_default_certificate check to aws-cloudfront-use-secure-tls-policy rule

- example/1087/main.tf
- internal/app/tfsec/rules/aws/vpc/add_description_to_security_group_rule.go
- internal/app/tfsec/rules/aws/vpc/add_description_to_security_group_rule_test.go
Resolves #1087
- ensure there is a description in ingress and egress blocks
- add tests to support
- add example
Doesn't support block as attribute format, they seem to be broken at a provider level at the moment
```hcl
ingress = [
{
// ingress bits
}
]
```
> Add check for description in blocks

- internal/app/tfsec/rules/aws/ecr/repository_customer_key_rule.go
[Good example](https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/rules/aws/ecr/repository_customer_key_rule.go#L53) of the ECR rule wrongly suggest to use KMS `key_id` instead of `arn` object.
From the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository#encryption_configuration):
> encryption_configuration
>    encryption_type - (Optional) The encryption type to use for the repository. Valid values are AES256 or KMS. Defaults to AES256.
kms_key - (Optional) The ARN of the KMS key to use when encryption_type is KMS. If not specified, uses the default AWS managed key for ECR.
As result if we using code from "good" example terraform would always detect false drift, as key_id is only part of ARN.
> Use KMS ARN in the ECR encryption good example

- .goreleaser.yml
Currently, there is a mix of indented and non-indented lists, as well as lists where the object follows on the next line and the same line.
This commit normalizes everything to the same type of lists, spacing build jobs with newlines to easily grok.
> Normalize spaces, newlines, lists

- internal/app/tfsec/adapter/azure/compute/adapt.go
- internal/app/tfsec/rules/azure/compute/disable_password_authentication_rule.go
- internal/app/tfsec/rules/azure/compute/enable_disk_encryption_rule.go
- internal/app/tfsec/rules/azure/compute/no_secrets_in_custom_data_rule.go
- internal/app/tfsec/rules/azure/compute/no_secrets_in_custom_data_rule_test.go
Write the adapters for the virtual machines and the managed disks
According to the Terraform docs: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#custom_data
the `custom_data` attribute is part of the `os_profile` block. Update examples and tests accordingly. 
Update examples and tests to include either `os_profile_linux_config` or `os_profile_windows_config` block. One of them is always required by Terraform depending on the os and as such is used by the adapter to classify the virtual machine by os.
Closes: https://github.com/aquasecurity/tfsec/issues/1233
> Azure compute - adapt to use defsec

- internal/app/tfsec/parser/load_module.go
- internal/app/tfsec/test/module_test.go
This PR fixes the issue with the terraform v1.1.0+ module sources
by changing matching on module source to matching on module name with module key in the json metadata file.
module source is since tf 1.1.0 no longer always equal to the source in the metadata json file(.terraform\modules\modules.json) ,for instance terraform/hashicorp auto resolves to registry.terraform.com, googleapis.com to gcs etc..
see issue #1188
> fix tf v1.1.0 init module sources

- internal/app/tfsec/adapter/azure/storage/adapt.go
- internal/app/tfsec/rules/azure/storage/allow_microsoft_service_bypass_rule.go
- internal/app/tfsec/rules/azure/storage/default_action_deny_rule.go
- internal/app/tfsec/rules/azure/storage/enforce_https_rule.go
- internal/app/tfsec/rules/azure/storage/no_public_access_rule.go
- internal/app/tfsec/rules/azure/storage/no_public_access_rule_test.go
- internal/app/tfsec/rules/azure/storage/queue_services_logging_enabled_rule.go
- internal/app/tfsec/rules/azure/storage/use_secure_tls_policy_rule.go
Write azure storage adapter.
Update resource `"azure_storage_container"` to `"azurerm_storage_container"` as per the latest [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_container).
Azure container resource in Terraform no longer includes a `properties` block and as such the `no_public_access_rule` has been modified to check the value in the `container_access_type` attribute. 
But it's up to the maintainers to decide if the rule should be kept at all.
An `"azurerm_storage_account"` resource has been added to the container examples, since its existence is already [required](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_container#storage_account_name) by Terraform, it is used to classify which account …
> Azure storage - adapt to use defsec logic

- internal/app/tfsec/adapter/aws/ecs/adapt.go
- internal/app/tfsec/rules/aws/ecs/enable_container_insight_rule.go
- internal/app/tfsec/rules/aws/ecs/enable_in_transit_encryption_rule.go
- internal/app/tfsec/rules/aws/ecs/no_plaintext_secrets_rule.go
- removed `CheckTerraform` from all 3 ECS rules
- added adaption code for ECS
Resolves #1262
> AWS ECS - convert tfsec checks to use defsec logic

- internal/app/tfsec/adapter/aws/cloudfront/adapt.go
- internal/app/tfsec/rules/aws/cloudfront/enable_logging_rule.go
- internal/app/tfsec/rules/aws/cloudfront/enable_logging_rule_test.go
- internal/app/tfsec/rules/aws/cloudfront/enable_waf_rule.go
- internal/app/tfsec/rules/aws/cloudfront/enforce_https_rule.go
- internal/app/tfsec/rules/aws/cloudfront/use_secure_tls_policy_rule.go
Write adapt functions
Add required `bucket` attribute to `logging` block in test (defsec checks this attribute's presence to determine whether logging is enabled).
Note: defsec only alerts when `viewer_protocol_policy` equals `allow_all`. As such in cases when the attribute is missing, `allow_all` is considered the default value even though it is not explicitly established as the default by Terraform. 
Closes #1284
> AWS CloudFront - adapt to use defsec

- internal/app/tfsec/adapter/aws/lambda/adapt.go
- internal/app/tfsec/rules/aws/lambda/enable_tracing_rule.go
- internal/app/tfsec/rules/aws/lambda/restrict_source_arn_rule.go
- internal/app/tfsec/rules/aws/lambda/restrict_source_arn_rule_test.go
- removed `CheckTerraform` from all 2 lambda rules
- added adaption code for lambda
- modified `restrict_source_arn_rule_test` (adding in the lambda functions for the permission resources to target)
Resolves #1282
> AWS lambda - convert tfsec checks to use defsec logic

- internal/app/tfsec/adapter/aws/sns/adapt.go
- internal/app/tfsec/rules/aws/sns/enable_topic_encryption_rule.go
- internal/app/tfsec/rules/aws/sns/enable_topic_encryption_rule_test.go
Resolves #1291
Fixed test "check with default encryption key id specified for aws_sns_topic fails check" as aws_kms_key does not accept key_id as an argument
> AWS SNS - convert tfsec checks to use defsec logic

- internal/app/tfsec/adapter/aws/elasticsearch/adapt.go
- internal/app/tfsec/rules/aws/elasticsearch/enable_domain_encryption_rule.go
- internal/app/tfsec/rules/aws/elasticsearch/enable_domain_logging_rule.go
- internal/app/tfsec/rules/aws/elasticsearch/enable_in_transit_encryption_rule.go
- internal/app/tfsec/rules/aws/elasticsearch/enforce_https_rule.go
- internal/app/tfsec/rules/aws/elasticsearch/use_secure_tls_policy_rule.go
- internal/app/tfsec/rules/aws/elasticsearch/use_secure_tls_policy_rule_test.go
Closes #1302 
Create adapter.
Update test to expect alert when `domain_endpoint_options` block is missing.
> AWS Elasticsearch - adapt to use defsec

- internal/app/tfsec/adapter/aws/athena/adapt.go
- internal/app/tfsec/rules/aws/athena/enable_at_rest_encryption_rule.go
- internal/app/tfsec/rules/aws/athena/enable_at_rest_encryption_rule_test.go
- internal/app/tfsec/rules/aws/athena/no_encryption_override_rule.go
Create adapter.
Update test to expect alert when `result_configuration` block is missing. 
Closes #1260
> AWS Athena - adapt to use defsec

- internal/app/tfsec/adapter/aws/dynamodb/adapt.go
- internal/app/tfsec/rules/aws/dynamodb/enable_at_rest_encryption_rule.go
- internal/app/tfsec/rules/aws/dynamodb/enable_at_rest_encryption_rule_test.go
- internal/app/tfsec/rules/aws/dynamodb/enable_recovery_rule.go
- internal/app/tfsec/rules/aws/dynamodb/table_customer_key_rule.go
- internal/app/tfsec/rules/aws/dynamodb/table_customer_key_rule_test.go
Since SSE is checked by https://github.com/aquasecurity/defsec/blob/master/rules/aws/dynamodb/enable_at_rest_encryption.go
case `"DynamoDB Table with disabled server side encryption fails check"` has been moved to the test file that corresponds to the mentioned check.
Closes #1313
> AWS DynamoDB adapt to use defsec

- internal/app/tfsec/custom/processing.go
- internal/app/tfsec/custom/processing_test.go
- did the above
- passing test case already exists, added fail test case
solves #1339
> custom checks: requiresPresence's subMatches now get processed too

- docs/getting-started/configuration/custom-checks.md
- internal/app/tfsec/custom/custom_check.go
- internal/app/tfsec/custom/custom_context.go
- internal/app/tfsec/custom/processing.go
- internal/app/tfsec/custom/processing_test.go
- take "name" value and store in map with index "assignVariable" value
- e.g. you can check that an attribute exists, and assign the attribute value to a variable
- variables must start with "TFSEC_VAR_"
- the variable can then be used in any following matchSpec "value" attributes
- added the above to the custom check docs
solves #1337
> add optional "assignVariable" attribute to "matchSpec"

- internal/app/tfsec/adapter/digitalocean/compute/adapt.go
`go mod vendor` is a bit weird to me. I tried to use `defsec == 0.3.20`, but that caused the AWS IAM adapters to break.
I'm not really sure about tests for this, and if it should be in defsec, or here. But I guess that's second to fetching the right dependencies. Keeping all of your dependencies in the repository, versus just having a file listing them (e.g., in Python) is one aspect of GoLang that's a bit peculiar to me, but I see positives of it.
> Add adapter for Digital Ocean Kubernetes

- .pre-commit-hooks.yaml
`tfsec` behavior when passing files instead of directories as CLI args is wierd.
If you pass one file, it fails:
```sh
tfsec main.tf 
The provided path is not a dir, exiting
```
However, if you pass more than one file, it works by assuming you want it to check the whole `$PWD`:
```sh
tfsec main.tf docker.tf 
times
------------------------------------------
disk i/o             571.658µs
parsing HCL          12.362µs
evaluating values    390.559µs
running checks       1.789988ms
counts
------------------------------------------
files loaded         3
blocks               10
modules              0
results
------------------------------------------
critical             0
high                 0
medium               0
low                  0
ignored              0
No problems detected!
```
Did …
> fix: avoid passing filenames to pre-commit hook

- .goreleaser.yml
The {{.Version}} placeholder strips the v of the front seemingly at random. Use {{.Tag}} for consistency
Resolves #1429
> fix: Fix the version at build time using Tag

- internal/app/tfsec/cmd/output.go
> fix: Handle output when terraform metadata is missing from rule

- internal/pkg/adapter/azure/keyvault/adapt.go
Resolves #1446 for expiration date failing when not a string
> fix: check that expiration date is a valid string

- internal/pkg/block/modules.go
Instead of matching the first referenced block to an attribute, we now check to see if a match is possible within the same module.
Resolves #1450
> fix: Always prefer matching a referenced block within the same module

- Dockerfile.ci
The README.md[0] define the tfsec-ci image as without `ENTRYPOINT` to
allow use to override the default command easily. It seems to me the
inlined documentation within the Dockerfile was not matching the
README.md one.
[0] https://github.com/aquasecurity/tfsec#use-with-docker
PS: Thanks for the project(s)
> fix: Match inlined comment and README.md image description

- internal/pkg/parser/load_vars.go
- internal/pkg/parser/load_vars_test.go
I needed this today and saw it was not there. I saw the issue getting marked with `good first issue`, so I wanted to jump on it 😬 Also I tried to add a simple test for parsing 👀 
Related Issue:
Resolves https://github.com/aquasecurity/tfsec/issues/1440
Related terraform code is here:
https://github.com/hashicorp/terraform/blob/c5740baa772fc65dcce5cb33be4b56f181073278/internal/command/meta_vars.go#L156
```
if strings.HasSuffix(filename, ".json") {
var hclDiags hcl.Diagnostics
f, hclDiags = hcljson.Parse(src, filename)
diags = diags.Append(hclDiags)
if f == nil || f.Body == nil {
return diags
}
} else {
var hclDiags hcl.Diagnostics
f, hclDiags = hclsyntax.ParseConfig(src, filename, hcl.Pos{Line: 1, Column: 1})
diags = diags.Append(hclDiags)
if f == nil || f.Body == nil {
return diags
}
} …
```
> feat: Add json support for tfvars files

- README.md
it was discussed in #1478 #1552, but the link of checks is still 404.
Since there is no `home/` , I thought it was correct and corrected it.
ex: https://aquasecurity.github.io/tfsec/latest/checks/aws/home/ -> https://aquasecurity.github.io/tfsec/latest/checks/aws/
> docs: fixed checks pages is 404

- internal/app/tfsec/cmd/output.go
> fix: lighten the permissions for results files

- go.mod
- go.sum
- internal/app/tfsec/cmd/flags.go
- test/flags_test.go
> feat(rego): Add --rego-only flag to run rego policies exclusively

- docs/guides/rego/rego.md
- docs/guides/usage.md
A couple of trivial fixes. The table is not rendered correctly because of the blank line between the rows with `verbose` and `var-file`.
> docs: Add link to Rego documentation

- docs/guides/github-actions/github-action.md
Branch names were backwards: `uses: actions/checkout@main` should be `@master`, whereas `uses: tfsec/tfsec-sarif-action@master` should be `@main`.
Note that the former, `actions/checkout@main` _does_ exist, it's just no longer the active branch.
> docs: fix branch names in sarif github action

- Makefile
- internal/pkg/formatter/default.go
- fix: infer no-code when concise output requested
- chore(deps): bump golang ci version
> fix: infer no-code when concise

- README.md
Building from the sources is not the preferred way and tfsec-bin uses the binary provided by this project (and checks the signature)
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tfsec
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tfsec-bin
> fix: prefer tfsec-bin AUR package

- docs/guides/quickstart.md
Fixes https://github.com/aquasecurity/tfsec/issues/1800
Just a simple fix. Here's a gif:
> GitHub Action link correction

- Makefile
- scripts/build.sh
Resolves #1849 - run build script using `make build`
Alternatively, just use `go build `
> fix: Fix build script

- docs/checks/aws/cloudtrail/ensure-cloudwatch-integration/index.md
- docs/checks/aws/cloudtrail/index.md
- docs/checks/aws/cloudtrail/no-public-log-access/index.md
- docs/checks/aws/cloudtrail/require-bucket-access-logging/index.md
- docs/checks/aws/ec2/index.md
- docs/checks/aws/ec2/no-public-ip-subnet/index.md
- docs/checks/azure/storage/queue-services-logging-enabled/index.md
- docs/checks/github/branch_protections/index.md
- docs/checks/github/branch_protections/require_signed_commits/index.md
- docs/checks/github/index.md
- docs/checks/google/iam/index.md
- mkdocs.yml
- ensure-cloudwatch-integration: checks/aws/cloudtrail/ensure-cloudwatch-integration
- no-public-log-access: checks/aws/cloudtrail/no-public-log-access
- require-bucket-access-logging: checks/aws/cloudtrail/require-bucket-access-logging
- no-public-ip-subnet: checks/aws/ec2/no-public-ip-subnet
- require_signed_commits: checks/github/branch_protections/require_signed_commits
Fixes https://github.com/aquasecurity/tfsec/issues/1881
> Add missing docs from recent additions to defsec

- docs/guides/configuration/config.md
- internal/app/tfsec/cmd/flags.go
- internal/pkg/config/config.go
- internal/pkg/config/config_test.go
- feat: add expiry to config file excludes
- docs: update docs for the config file
Resolves #1896
> feat: support exclude expiry in config

- .github/workflows/stale.yml
- Set github stale bot message "days" to its config
- It's confusing when the message says that the stale bot will close the issue/pr in X number of days and that X number of days is not the same as the days configured in the bot itself. This change should set the numbers to be the same.
- https://github.com/aquasecurity/tfsec/issues/1943
> Set github stale bot message "days" to its config

- docs/checks/aws/elb/drop-invalid-headers/index.md
> fix typo of drop-invalid-headers doc

- scripts/install_linux.sh
https://github.com/aquasecurity/tfsec/issues/1986
> fix: sha256 command

- README.md
Related to the tasks in the following issue  #2016
> docs: README tfsec to trivy migration callout

- cmd/tfsec/main.go
The transition message disable us to parse the result of JSON format. So, it would be good to print out the message as standard error. 
I tested the change locally. I was able to parse the results with a `jq` command.
```
$ /Users/***/local/src/github/tfsec/bin/darwin/tfsec-darwin-amd64 . --format json | jq -r '.'
======================================================
tfsec is joining the Trivy family
tfsec will continue to remain available
for the time being, although our engineering
attention will be directed at Trivy going forward.
You can read more here:
https://github.com/aquasecurity/tfsec/discussions/1994
======================================================
{
"results": []
}
```
> Print the transition message as standard error

- go.mod
- go.sum
github.com/hashicorp/go-getter v1.7.0 has a CRITICAL vunerability.
Just updating to github.com/hashicorp/go-getter v1.7.4 would fix it.
github.com/hashicorp/go-getter │ CVE-2024-3817  │ CRITICAL │ v1.7.0     │ 1.7.4     │ HashiCorp\u2019s go-getter library is vulnerable to argument 
https://avd.aquasec.com/nvd/cve-2024-3817
> Bumped hashicorp/go-getter due Critical Vulnerability

- go.mod
- go.sum
github.com/hashicorp/go-getter v1.7.4 has a HIGH vunerability.
Just updating to github.com/hashicorp/go-getter v1.7.5 would fix it.
https://avd.aquasec.com/nvd/cve-2024-6257
> Bumped Go-Getter due High Vulnerability CVE-2024-6257

- .github/workflows/golangci-lint.yml
- .golangci.yml
- Makefile
This updates golangci-lint to v1.63.4 and clean up it’s configuration
> chore: update and clean up golangci-lint
